import type {MuseumAssetId} from './museumAssetTypes';
import type {MuseumPrimaryInterpretationEnrichment} from './scholasticRationalistPrimaryInterpretationEnrichment';

type VisitorGuideSection = {
  readonly heading: string;
  readonly items: readonly {readonly label: string; readonly description: string}[];
};

const objectLed = (
  name: string,
  paragraphs: readonly string[],
  orientation: readonly VisitorGuideSection[],
  assetId: MuseumAssetId,
  objectText: string,
  lock: `fnv1a64:${string}`,
): MuseumPrimaryInterpretationEnrichment => ({
  lead: '',
  keyIdeas: [],
  keyWorks: [],
  sections: [{heading: '', paragraphs}],
  presentation: {
    mode: 'concise',
    orientation,
    articleActionLabel: `Read the full sourced ${name} article`,
    bodyLayout: 'prose',
    exhibitLayout: 'object-led',
    plaqueKicker: '',
    plaqueSubtitleLines: 4,
  },
  objectInterpretations: {[assetId]: objectText},
  review: {
    status: 'standard-compliant',
    reviewedOn: '2026-08-09',
    method: 'Reconciled against the current claim-reviewed article, registered sources, and principal-object provenance; object-led presentation and subject-specific visitor guide reviewed against the locked exhibit standard.',
    lock,
  },
});

/**
 * Consecutive claim-reviewed canonical exhibits after the first two completed
 * groups. Each record is a title-local Museum interpretation, not an
 * abridgement of the corresponding full sourced canonical article.
 */
export const CANONICAL_ORDER_PRIMARY_INTERPRETATIONS_C:
Readonly<Record<string, MuseumPrimaryInterpretationEnrichment>> = {
  hegel: objectLed(
    'Hegel',
    [
      'Hegel asks how freedom can become actual rather than remain a private wish or an abstract rule. Reason, for him, takes shape through language, work, law, family, civil society, political institutions, art, religion, and philosophy. A form of life can expose the limits of its own self-understanding: someone who calls freedom mere independence discovers reliance on recognition, shared norms, and institutions; an institution that promises equality can reveal exclusions it cannot justify. This is why dialectic is not a mechanical sequence of thesis, antithesis, and synthesis. It is an attempt to follow a position’s internal pressures toward a more adequate account of what it already claims.',
      'In the Phenomenology, consciousness repeatedly loses a certainty that proves too thin; the lordship-and-bondage episode is one analysis of failed recognition, not a ready-made prophecy of class struggle. The Logic examines categories of being, essence, and concept rather than offering modern symbolic logic. The Philosophy of Right connects legal personhood, morality, family, civil society, and state, but it does not make Hegel a simple worshipper of whatever government exists or a straightforward modern democrat. His monarchical and hierarchical institutions, poverty problem, gendered division of social roles, Eurocentric history, racialized anthropology, and colonial hierarchy are consequential limits, not detachable footnotes to freedom.',
      'Jakob Schlesinger painted this lifetime portrait in 1831, the year Hegel died. It identifies a late-career philosopher and the formal public image made of him; it cannot display a dialectical transition, prove that the system is closed, or settle disputes over logic, politics, religion, Haiti, race, or colonialism. It also cannot authenticate the many lecture volumes edited from manuscripts and student notes after his death. The portrait is best used as a historical anchor while the dated, differently authorized texts and the arguments they invite remain open to critical reading.',
    ],
    [
      {heading: 'How the method works', items: [
        {label: 'Dialectic', description: 'A position is tested through tensions generated by its own commitments; the result is not a formula that always produces a middle compromise.'},
        {label: 'Recognition', description: 'A person becomes socially intelligible as free and responsible through reciprocal standing, not through inward self-awareness alone.'},
      ]},
      {heading: 'Freedom in institutions', items: [
        {label: 'Ethical life', description: 'Family, civil society, and political institutions are practices through which freedom can gain durable social form, not merely limits imposed on individuals.'},
        {label: 'The rational state', description: 'Hegel’s normative ideal is not every existing government; its relation to monarchy, bureaucracy, participation, poverty, and coercion remains contested.'},
      ]},
      {heading: 'Read with caution', items: [
        {label: 'Lecture texts', description: 'Posthumously edited courses on art, religion, history, and philosophy are indispensable but differ in authority from Hegel’s lifetime-published books.'},
        {label: 'Later Hegels', description: 'Marxists, existentialists, critical theorists, anticolonial thinkers, and recognition theorists transformed Hegel rather than simply repeating his doctrine.'},
      ]},
    ],
    'german-idealism-hegel-schlesinger-1831',
    'Jakob Schlesinger’s 1831 oil portrait, held by Berlin’s Alte Nationalgalerie, is a lifetime likeness of Georg Wilhelm Friedrich Hegel in formal dress. It establishes a formal image made in his final year, but cannot show dialectic, prove a closed system, settle political or colonial controversies, or authenticate the posthumously edited lecture courses. The painting identifies a philosopher; the differently authorized texts and their disputes establish the philosophy.',
    'fnv1a64:092c1a4f2b1b0c40',
  ),
  bentham: objectLed(
    'Bentham',
    [
      'Jeremy Bentham begins with a demand that is both simple and disruptive: law and policy should be judged by their effects on pleasure, pain, security, and well-being, not by inherited rank, opaque legal language, or approval alone. The principle of utility asks legislators to count every affected sentient interest. Its familiar “felicific calculus” names circumstances that should discipline judgment—such as intensity, duration, likelihood, and extent—not a machine that can settle every choice. Bentham’s question about animals is similarly not a sentimental aside: sentience changes who must enter the moral and legal calculation, even when the institutional answers remain difficult.',
      'Bentham brought that standard into jurisprudence, evidence, procedure, punishment, poor relief, political economy, democracy, and constitutional reform. He attacked legal fictions and common-law mystery while seeking codification and public reasons. The Panopticon was a proposal for inspection, discipline, economy, and administration, not a neutral architectural curiosity; it makes the tension in his reforming ambition visible. A policy designed to reduce arbitrary suffering can also sort, supervise, and render vulnerable people administratively legible. His democratic and sexual-liberty arguments, writings on empire and transportation, and vast unevenly published manuscript corpus resist a tidy image of one finished “Benthamism.”',
      'The object is Bentham’s auto-icon at University College London: his preserved skeleton and clothing arranged in a glass case, with a wax replacement head. It records his unusual posthumous plan for continuing public usefulness and the later institutional management of that plan. It is not a lifetime likeness, evidence that Bentham founded UCL, or a demonstration of utility, surveillance, punishment, or reform. Its uneasy material afterlife is nevertheless instructive: a philosophy of public institutions can itself become an institution, whose display asks visitors to examine both the promise of accountability and the power to arrange persons for public view.',
    ],
    [
      {heading: 'The utilitarian test', items: [
        {label: 'Utility', description: 'A demand to assess consequences for those affected, rather than treating custom, title, or legal vocabulary as its own justification.'},
        {label: 'Sentience', description: 'The capacity to suffer matters morally; this widens concern beyond citizens and challenges exclusion from the calculation.'},
      ]},
      {heading: 'Law as a public craft', items: [
        {label: 'Codification', description: 'Bentham sought laws that could be publicly understood, criticized, and revised instead of relying on professional mystery and precedent alone.'},
        {label: 'Panopticon', description: 'A proposed inspection house whose promise of efficient oversight also raises enduring questions about surveillance and administrative power.'},
      ]},
      {heading: 'A divided legacy', items: [
        {label: 'Rights and reform', description: 'Bentham criticized natural rights while pursuing legal protections and political reforms, a distinction often obscured by the slogan “nonsense upon stilts.”'},
        {label: 'Manuscripts and reception', description: 'Published books, private manuscripts, critical editions, and later Benthamite programs do not all have the same public status or authority.'},
      ]},
    ],
    'utility-bentham-auto-icon',
    'Ben Paulos’s 2014 photograph shows Jeremy Bentham’s auto-icon at University College London: Bentham’s preserved skeleton and clothes in a display case, with a wax replacement head. It documents a posthumous arrangement and its later public care, not Bentham’s living appearance, authorship of UCL, or the truth of utilitarianism. The object can illuminate institutional afterlife and display; it cannot settle the moral or political claims of his reform projects.',
    'fnv1a64:cc6eb7f16d150342',
  ),
  mill: objectLed(
    'Mill',
    [
      'John Stuart Mill revised utilitarianism by asking what kinds of lives a politics of happiness should make possible. Well-being is not a pile of interchangeable satisfactions: cultivated capacities, individuality, relationships, imagination, and self-development matter. His distinction between higher and lower pleasures is not a settled proof that some enjoyments can be measured on one ladder; it opens disputes about dignity, competence, and whether his view remains purely hedonistic. Mill’s wider work on logic, political economy, representative government, women’s equality, and religion makes On Liberty one important part of a developing project rather than a free-standing manifesto.',
      'The harm principle protects competent adults against coercion in their self-regarding conduct, but it is not a rule that forbids all regulation or blesses every choice. Mill distinguishes duties to others, dangerous contexts, children, and limits of capacity; his defense of open discussion turns on fallibility, partial truth, and the need to keep convictions alive through contest. His writing with and about Harriet Taylor Mill belongs to this intellectual history, although exact coauthorship claims require care. Mill also defended women’s equality and studied cooperation, distribution, and participation while proposing competence-weighted devices and working for the East India Company. His imperial civilizational exception sharply limits any easy identification of liberty with universal anti-paternalism.',
      'George Frederic Watts painted this late lifetime portrait in 1873, the year Mill died. The canvas provides a likeness of an aging public intellectual, not a picture of utility, individuality, social tyranny, Taylor’s contribution, or empire. It cannot make Mill’s corpus more harmonious than its revisions and tensions warrant. The quiet, solitary pose is a useful counterweight to a simplified icon of “liberty”: the philosophy asks about social formation, discussion, education, institutions, and unequal power as well as an individual’s protected space for experiment.',
    ],
    [
      {heading: 'Utility and development', items: [
        {label: 'Qualitative pleasure', description: 'Mill argues that developed human capacities matter to happiness, a claim that invites debate about competence, dignity, and the meaning of well-being.'},
        {label: 'Experiments in living', description: 'Different ways of life can test inherited custom and help people develop judgment, provided their consequences for others are taken seriously.'},
      ]},
      {heading: 'Liberty’s boundaries', items: [
        {label: 'Harm principle', description: 'A limit on coercing competent adults in their own conduct, not an exemption from duties, regulation of dangerous contexts, or responsibility for others.'},
        {label: 'Free discussion', description: 'Dissent matters because people and societies are fallible, not because every utterance has identical force, reach, or consequence.'},
      ]},
      {heading: 'A contested reformer', items: [
        {label: 'Harriet Taylor Mill', description: 'Mill’s collaborator and intellectual partner; her influence is substantial while exact authorship of particular texts remains disputed.'},
        {label: 'Empire and competence', description: 'Mill’s arguments for liberty were narrowed by developmental hierarchy and his East India Company world, a tension integral to the record.'},
      ]},
    ],
    'utility-mill-watts-portrait',
    'George Frederic Watts’s 1873 portrait at Watts Gallery is a lifetime likeness of John Stuart Mill, painted in the year of his death. It identifies a late-career thinker, but cannot make utility, liberty, equality, collaboration with Harriet Taylor Mill, representative government, or imperial exception visible in expression alone. The canvas anchors historical identity; the changing texts and their contested political scope establish the argument.',
    'fnv1a64:de7b4f1b4945be3b',
  ),
  marx: objectLed(
    'Marx',
    [
      'Karl Marx makes social production the place where freedom, domination, and historical change must be examined. People do not meet one another only as isolated choosers: they work, own or lack property, exchange, organize households, make institutions, and inherit relations they did not create. Early writing on alienated labor asks how workers’ activity and products can confront them as an alien power. Marx’s move from Hegelian and Feuerbachian critique toward praxis does not reject thought; it asks critique to explain the material relations that reproduce an illusion and the collective activity through which those relations might change.',
      'Capital studies commodities, money, labor power, surplus value, accumulation, machinery, and the world market as forms whose ordinary operation can obscure their social character. Historical materialism is a later label for a changing set of arguments, not a timetable in which technology mechanically dictates every belief or inevitable revolution. Marx wrote journalism, polemic, collaborative texts with Friedrich Engels, published books, unfinished manuscripts, and works later edited after his death; those genres cannot simply be fused into one final system. His account leaves live disputes over value, exploitation, justice, transition, race, colonialism, gender and social reproduction, ecology, and the institutional meaning of self-emancipation.',
      'Richard Beard photographed Marx in London in May 1861, during the long years of research, journalism, organizing, illness, and financial strain before the first volume of Capital appeared in 1867. It is a documented lifetime image and not the familiar 1875 Mayall portrait. The photograph cannot reveal a theory of value, establish a political blueprint, or make every later Marxist state or movement Marx’s direct doctrine. It gives the exhibit a particular historical person while preserving a distinction crucial to the collection: the arguments, their editions, and the later institutions claiming their authority require separate judgment.',
    ],
    [
      {heading: 'Critique begins in practice', items: [
        {label: 'Praxis', description: 'Human beings transform nature and social life through collective activity; critique asks how that activity is organized and constrained.'},
        {label: 'Alienation', description: 'A structural condition in which workers’ products, labor, and social powers confront them as someone else’s property or command.'},
      ]},
      {heading: 'Political economy', items: [
        {label: 'Commodity form', description: 'Goods appear to exchange as things with prices, while the labor and social relations that produce them can become obscured.'},
        {label: 'Surplus value', description: 'Marx’s account of how owners appropriate value produced beyond what labor power costs, central to his analysis and still disputed.'},
      ]},
      {heading: 'Read a changing corpus', items: [
        {label: 'Historical materialism', description: 'A later umbrella label for arguments about production, property, institutions, and struggle—not an automatic theory of historical destiny.'},
        {label: 'Marx and Marxism', description: 'Later socialist, communist, feminist, anticolonial, ecological, and critical traditions developed, disputed, and sometimes transformed Marx’s work.'},
      ]},
    ],
    'utility-marx-1861-beard-portrait',
    'Richard Beard’s May 1861 London photograph shows Karl Marx standing beside a chair before Capital’s first volume appeared in 1867. It is a lifetime likeness, distinct from the better-known 1875 Mayall portrait, and can situate a writer working through research, journalism, and political organization. It cannot picture value, exploitation, class, or historical materialism, supply a political blueprint, or make later regimes and movements direct evidence of Marx’s own doctrine.',
    'fnv1a64:900a9c6967ee66c0',
  ),
  schopenhauer: objectLed(
    'Schopenhauer',
    [
      'Arthur Schopenhauer begins from a Kantian limit: the world we encounter is representation, ordered for a subject through space, time, causation, and other forms of explanation. He then gives embodiment unusual force. My body is encountered externally as an object among objects and internally in effort, desire, resistance, and action; Schopenhauer identifies this inwardly known striving with will and generalizes it across nature. Will is not ordinary deliberate choice, and will and representation are not two separately existing worlds. The inference from one’s own embodied experience to a universal metaphysics is the system’s daring, contestable move rather than an empirical discovery it can simply announce.',
      'Pessimism follows from the recurring structure of willing: satisfaction removes one lack only for another to emerge, while conflict, vulnerability, boredom, and competition remain built into striving. This is not a mood or a claim that nothing matters. Art offers temporary contemplative release from interested desire; music receives an exceptional metaphysical role; compassion interrupts egoistic separation; ascetic denial seeks a more radical quieting. Schopenhauer’s encounter with Upanishadic and Buddhist materials was philosophically consequential but mediated through the Persian-to-Latin Oupnek’hat, European scholarship, and Orientalist categories. It was not Sanskrit mastery, membership in an Asian tradition, or proof of doctrinal identity. His misogynist, racialized, antisemitic, and culturally hierarchical writings are likewise part of the corpus and strain its ethics of compassion.',
      'J. Schäfer’s March 1859 photograph shows Schopenhauer in Frankfurt near the late recognition of his work, cane in hand. It is a lifetime likeness, though Commons does not supply the photographer’s first name. The image can establish neither a person’s philosophical temperament nor the truth of pessimism, will, compassion, or asceticism. Its direct gaze should not turn a composed portrait into psychological evidence. Instead, it frames a thinker whose challenging claim is conceptual: whether the felt pressure of striving discloses a deeper unity in nature or merely invites an overextended metaphysical interpretation.',
    ],
    [
      {heading: 'Two ways of knowing a body', items: [
        {label: 'Representation', description: 'The experienced world appears in relation to a knowing subject and through forms such as space, time, and causation.'},
        {label: 'Will', description: 'Blind, aim-renewing striving disclosed in embodied action and generalized by Schopenhauer beyond ordinary conscious choice.'},
      ]},
      {heading: 'Responses to suffering', items: [
        {label: 'Aesthetic contemplation', description: 'Absorbed attention can briefly suspend interested striving; Schopenhauer gives music a distinctive metaphysical role.'},
        {label: 'Compassion and asceticism', description: 'Concern for another’s suffering and the more radical quieting of will are related but different ethical responses.'},
      ]},
      {heading: 'Important limits', items: [
        {label: 'Mediated Indian reception', description: 'The Oupnek’hat and European scholarship were routes of selective reception, not direct access to all Upanishadic or Buddhist traditions.'},
        {label: 'Prejudice in the corpus', description: 'His categorical claims about women, Jews, race, and culture cannot be excused by later influence or detached from his philosophy.'},
      ]},
    ],
    'value-schopenhauer-schaefer-portrait',
    'J. Schäfer’s March 1859 photograph at Frankfurt am Main University Library is a lifetime likeness of Arthur Schopenhauer during his late public recognition; the source identifies the photographer only as “Schäfer, J.” It can identify the sitter, not disclose his temperament or prove pessimism, will, compassion, or asceticism. The composed image provides historical presence while the body argument, its scope, and its ethical tensions remain matters for the texts and their critics.',
    'fnv1a64:1b581062de4a4fcc',
  ),
  kierkegaard: objectLed(
    'Kierkegaard',
    [
      'Søren Kierkegaard asks what it means to become a self when a system, a crowd, or a cultural role cannot make the decisive commitment for anyone. He writes through pseudonymous books, signed discourses, journals, devotional works, satire, and a late attack on Danish Christendom. These are not transparent masks for one private doctrine. Johannes de Silentio, Johannes Climacus, Anti-Climacus, aesthetic voices, and Judge William speak from different positions, genres, and limits; their distance from the author is part of the philosophical work. “Stages” or spheres of aesthetic, ethical, and religious existence are recurring orientations, not a universal three-rung ladder every person must climb.',
      'Anxiety names the dizzying possibility of freedom, not simply clinical distress. Despair is a self’s failure to relate truthfully to itself and to the power that grounds it; repetition, promise, neighbor-love, and ethical continuity complicate any picture of heroic arbitrary choice. Fear and Trembling, voiced by Johannes de Silentio, poses the Abraham problem without granting institutions or private persons a reusable exemption from ethics. Kierkegaard’s later polemic against Christendom challenges inherited membership and comfortable admiration without imitation. Yet his critique of crowd and public is not a democratic political program; conservative tendencies, hierarchy, gender limits, and Christian exclusivity remain part of what later existentialist and theological receptions transform or contest.',
      'Luplau Janssen painted Kierkegaard at a writing desk around 1902, nearly five decades after his death. The posthumous reconstruction makes writing and revision visible, but it is not a lifetime likeness and cannot turn the pseudonyms into one direct authorial voice. Nor can it decode Regine Olsen, the Corsair affair, a journal entry, or a particular work through biographical atmosphere. The image earns its place when it presses a formal question: how do literary voices make a reader responsible for interpretation, rather than supplying a doctrine that can be borrowed without personal risk?',
    ],
    [
      {heading: 'A deliberately multiple authorship', items: [
        {label: 'Indirect communication', description: 'Pseudonyms, irony, and form make readers encounter a standpoint’s attraction and limits instead of receiving one simple authorial conclusion.'},
        {label: 'Signed and late writings', description: 'Discourses, Works of Love, journals, and the direct attack on Christendom have different voices and evidential roles.'},
      ]},
      {heading: 'Existence and commitment', items: [
        {label: 'Anxiety and despair', description: 'Possibility can unsettle freedom, while despair names distorted ways a self relates to itself and its grounding.'},
        {label: 'Faith and ethics', description: 'The Abraham problem remains a paradox and danger, not a general religious permission to suspend ethical responsibility.'},
      ]},
      {heading: 'Reception with limits', items: [
        {label: 'Works of Love', description: 'Neighbor-love joins religious inwardness to demanding equality and responsibility, without becoming a ready-made modern political program.'},
        {label: 'Existentialism', description: 'Later thinkers inherited anxiety, choice, and existence while often transforming or omitting Kierkegaard’s explicitly Christian project.'},
      ]},
    ],
    'value-kierkegaard-copenhagen-portrait',
    'Luplau Janssen’s c. 1902 painting at Frederiksborg Castle imagines Søren Kierkegaard reading at a high writing desk. Made nearly five decades after his death, it is a posthumous reconstruction rather than a lifetime likeness. It can evoke authorship and reading, but cannot authenticate a pseudonym’s claim, reveal Kierkegaard’s inward life, decode Regine Olsen, or collapse signed works, journals, discourses, and late polemics into one voice.',
    'fnv1a64:5803b33def9ca86e',
  ),
  peirce: objectLed(
    'Peirce',
    [
      'Charles Sanders Peirce makes inquiry a disciplined response to genuine doubt, not a method for defending whatever one already prefers. A settled habit is disrupted; investigators propose explanations, draw consequences, test them, and remain answerable to evidence and future correction. His pragmatic maxim asks what conceivable practical bearings a concept would have, a demand for clarity that is not the slogan “whatever works.” The long-run ideal of inquiry pictures an indefinitely self-correcting community rather than predicting that any present majority, institution, or scientific consensus is automatically true. Fallibilism is therefore neither despair about knowledge nor permission to treat every claim as equally secure.',
      'Peirce’s logic of signs broadens the scene. A sign relates to an object through an interpretant, the effect or further sign through which it is understood; the familiar icon, index, and symbol are only one evolving classification within a much larger semiotics. Abduction proposes a plausible explanatory hypothesis, deduction traces what would follow, and induction tests patterns against experience. These are distinct tasks, not a single ladder that mechanically produces discovery. Peirce’s work in measurement, astronomy, geodesy, logic, and philosophy supports his attention to standards, error, and public testability, but his immense corpus is unfinished and multiply edited. No one vocabulary list captures its development or resolves disputes over realism, truth, continuity, and the scope of pragmatism.',
      'The principal photograph shows Peirce at Harvard graduation in 1859, before his mature pragmatist and semiotic writings. The sitter is identified, but the photographer is unknown. It can establish a young historical person and remind visitors that a long intellectual career develops through institutions and practices; it cannot portray a sign relation, demonstrate abduction, or prove the eventual convergence of inquiry. Its strength is chronological restraint. The image keeps the exhibit from treating Peirce’s later technical ideas as a timeless portrait of genius detached from the fallible, collective work they describe.',
    ],
    [
      {heading: 'Inquiry without final certainty', items: [
        {label: 'Genuine doubt', description: 'Inquiry begins when a real disruption unsettles a habit of belief, not when someone manufactures skepticism for a classroom exercise.'},
        {label: 'Fallibilism', description: 'Any belief may require correction, while evidence and disciplined testing can still make some claims better warranted than others.'},
      ]},
      {heading: 'Making and testing ideas', items: [
        {label: 'Pragmatic maxim', description: 'Clarify a concept by asking about its conceivable practical bearings, not by equating truth with immediate usefulness or popularity.'},
        {label: 'Abduction, deduction, induction', description: 'Generate a hypothesis, trace its consequences, and test it against experience; each reasoning form does different work.'},
      ]},
      {heading: 'A changing technical corpus', items: [
        {label: 'Signs and interpretants', description: 'Meaning is mediated through effects of interpretation; Peirce’s sign classifications changed across a large, unfinished body of work.'},
        {label: 'Community of inquiry', description: 'Public standards, criticism, measurement, and correction matter more than a private certainty or any current consensus.'},
      ]},
    ],
    'peirce-harvard-graduation-portrait-1859',
    'This 1859 Harvard graduation photograph identifies the young Charles Sanders Peirce; the image is held in the Tuttle Collection at Texas Tech University, while the photographer is unknown. It predates his mature pragmatist and semiotic writings. The photograph can establish a lifetime sitter and early setting, but cannot show a sign relation, demonstrate abduction, prove fallibilism, or guarantee a final consensus in inquiry.',
    'fnv1a64:9158631c33d2eedf',
  ),
  'william-james': objectLed(
    'William James',
    [
      'William James treats experience as more various, unfinished, and practically consequential than a philosophy built around one completed system can allow. In The Principles of Psychology, attention, habit, emotion, self, and the stream of thought make minded life a process rather than a sequence of isolated ideas. His pragmatism asks what difference a belief makes in experience and action, but pragmatic truth is not whatever produces an immediate payoff. Experience can resist a belief; beliefs must cohere with other truths and remain vulnerable to correction. James’s pluralism likewise does not make the world incoherent: it denies that unity, necessity, and final harmony are guaranteed in advance by a single metaphysical whole.',
      'The Will to Believe permits a risk of commitment only in a live, forced, momentous option that cannot be settled in advance; it is not a general permission for wishful belief. The Varieties of Religious Experience investigates the fruits and authority of religious life without proving a theology, and radical empiricism develops a further account of relations and “pure experience” that should not be collapsed into either psychology or the stream of consciousness. James’s early Thayer Expedition also belongs to the record: it formed part of nineteenth-century field science and its racialized institutions, without by itself proving endorsement of every racial claim associated with Louis Agassiz. James is curious about experience while attentive to the conditions under which testimony, observation, and authority travel.',
      'Sarah Wyman Whitman painted this lifetime portrait in 1903, held by Harvard Art Museums. It gives James a public presence, facing forward with a book in hand, but cannot document a particular lecture, experiment, religious experience, or philosophical doctrine. The portrait’s composure should not turn temperament into proof. Its value is to hold together a writer and teacher with questions that resist biography: what may belief risk, how do experiences become evidence, and how can a plural world be investigated without mistaking provisional success for certainty?',
    ],
    [
      {heading: 'Experience and inquiry', items: [
        {label: 'Stream of thought', description: 'Conscious life is a moving, selective process, not a collection of separate ideas that can simply be counted or stored.'},
        {label: 'Pragmatic truth', description: 'A belief’s experiential consequences, resistance, coherence, and capacity for correction matter; usefulness alone does not make it true.'},
      ]},
      {heading: 'Risk and plurality', items: [
        {label: 'The will to believe', description: 'A bounded case for commitment when an option is live, forced, momentous, and not decidable before one must act.'},
        {label: 'Pluralism', description: 'Reality may contain genuine alternatives and local unities without being guaranteed by a single finished rational system.'},
      ]},
      {heading: 'Difficult evidence', items: [
        {label: 'Religious experience', description: 'James studies its varieties and effects without treating private report as a proof of one theology or a substitute for criticism.'},
        {label: 'Field science and race', description: 'His Thayer Expedition participation belongs to a racialized scientific context and requires scrutiny without unsupported conclusions about every belief.'},
      ]},
    ],
    'william-james-whitman-painted-portrait-1903',
    'Sarah Wyman Whitman’s 1903 painting, held by Harvard Art Museums, is a lifetime portrait of William James in formal academic dress with a book. It establishes a public likeness, not the content of a lecture, experiment, religious experience, pragmatist argument, or pluralist metaphysics. The portrait can anchor a historical thinker while questions about experience, belief, evidence, and truth remain answerable only through the texts, practices, and controversies around them.',
    'fnv1a64:c8fc6342fee426a5',
  ),
};
