import type {MuseumPrimaryInterpretationEnrichment} from './scholasticRationalistPrimaryInterpretationEnrichment';

const objectInterpretations=(entries:readonly (readonly [string,string])[])=>Object.fromEntries(entries);

export const FINAL_UNIVERSAL_DEPTH_PRIMARY_INTERPRETATIONS:
Readonly<Record<string,MuseumPrimaryInterpretationEnrichment>>={
  'philippa-foot':{
    lead:'Philippa Foot asks how moral judgments can be answerable to facts and reasons without becoming either expressions of attitude or commands written directly into biology.',
    keyIdeas:[],
    keyWorks:[],
    sections:[{heading:'',paragraphs:[
      'Philippa Foot asked how moral judgments can be answerable to facts and reasons without becoming either expressions of attitude or commands written directly into biology. Her early essays challenged emotivism and prescriptivism by reconnecting evaluation with harm, benefit, virtue, and the circumstances of human life. Justice and benevolence matter because people are vulnerable, dependent, and able to recognize claims beyond present desire. Yet Foot’s position changed: in 1972 she doubted that morality’s rational authority had been established, while Natural Goodness later rebuilt that authority through an account of human practical reason.',
      'The runaway trolley entered this larger project in Foot’s 1967 paper on abortion and double effect. Her driver could redirect an existing threat from five people toward one. The case tested intention, doing and allowing, and duties not to injure versus duties to aid; it was not Thomson’s later bystander or footbridge case, and it was never Foot’s complete ethics. Her work on euthanasia likewise distinguishes justice, charity, killing, allowing death, harm, and benefit rather than assuming that one contrast decides every case.',
      'Natural Goodness places moral evaluation within the evaluative grammar used for living things. Roots may be defective relative to an oak’s life; human willing may be defective relative to a life involving language, promise, dependence, deliberation, and shared goods. This does not make what is common, medically typical, or evolutionarily successful morally right. Critics ask whether life-form standards can ground normativity without excluding human variation or importing hierarchy, and whether justice remains rational when vice benefits the agent. The botanical object visualizes an analogy, not a biological moral ledger.',
    ]}],
    presentation:{mode:'concise',orientation:[
      {label:'Historical setting',value:'Oxford analytic ethics after emotivism and prescriptivism'},
      {label:'Development',value:'Moral beliefs · virtues · hypothetical imperatives · natural goodness'},
      {label:'Moral relations',value:'Justice · benevolence · reasons · practical rationality'},
      {label:'Hard cases',value:'Abortion · double effect · euthanasia · the original trolley comparison'},
      {label:'Open dispute',value:'Whether life-form evaluation can ground normativity without hierarchy'},
    ],articleActionLabel:'Read the full sourced Philippa Foot article',bodyLayout:'prose',plaqueKicker:'',plaqueSubtitleLines:4},
    objectInterpretations:objectInterpretations([
      ['moral-foot-somerville-1939','The Somerville group photograph is a historical setting, not a securely identified individual portrait: the archive describes Foot’s presence but does not establish where she stands. The exhibit therefore makes no face-level identification.'],
    ]),
  },
  'judith-thomson':{
    lead:'Judith Jarvis Thomson analyzes morality through structured relations among persons: rights, duties, permissions, claims, bodily use, harm, and aid.',
    keyIdeas:[],
    keyWorks:[],
    sections:[{heading:'',paragraphs:[
      'Judith Jarvis Thomson analyzed morality through structured relations among persons: rights, duties, permissions, claims, bodily use, harm, and aid. “A Defense of Abortion” conditionally grants that a fetus is a person with a right to life, then asks what follows. The violinist shows that a right to life need not include a right to another person’s body. The paper distinguishes strict justice from being a Good or Minimally Decent Samaritan, so permission is not the same as kindness and bodily authority is not a comprehensive theory of pregnancy, personhood, or care.',
      'Consent and responsibility remain contested within the argument. Thomson’s people-seeds case asks whether taking precautions while accepting a risk grants a dependent being a claim to bodily support; critics answer that pregnancy and parenthood are not like kidnapping or intrusion. Her later Realm of Rights broadens the inquiry. It examines claims, privileges, powers, duties, enforcement, and tradeoffs; distinguishes human rights against killing or harm from rights generated by promises, consent, and legitimate law; and does not treat need or possession as automatically creating an enforceable claim.',
      'Her trolley cases also changed. Foot introduced a driver’s redirection in 1967. Thomson named the problem in 1976, introduced Bystander at the Switch and Footbridge in 1985, and in 2008 reversed her judgment that the bystander may turn the trolley onto one person. The sequence shows cases functioning as revisable tests, not intuition polls or a moral algorithm. Self-defense presents the same discipline: guilt, threat, innocence, agency, and who has a claim against whom can come apart. The displayed diagram is a later explanation, neither Thomson’s portrait nor an artifact she made, and it must not collapse Foot’s and Thomson’s different cases.',
    ]}],
    presentation:{mode:'concise',orientation:[
      {label:'Method',value:'Controlled cases that expose the structure of rights and permissions'},
      {label:'Bodily claims',value:'Violinist · consent · responsibility · Samaritan duties'},
      {label:'Mature theory',value:'Claims · privileges · powers · enforcement · property'},
      {label:'Trolley chronology',value:'Foot 1967 · Thomson 1976 and 1985 · reversal in 2008'},
      {label:'Open disputes',value:'Positive duty · self-defense · killing and allowing · social context'},
    ],articleActionLabel:'Read the full sourced Judith Jarvis Thomson article',bodyLayout:'prose',plaqueKicker:'',plaqueSubtitleLines:4},
    objectInterpretations:objectInterpretations([
      ['moral-thomson-trolley-problem','The trolley diagram is a modern explanatory image, not a work by Thomson or a likeness of her. Its simplified tracks omit history, bodies, institutions, and the changes in Thomson’s own view.'],
    ]),
  },
  'thomas-nagel':{
    lead:'Thomas Nagel asks what increasingly objective understanding gains and what it can leave out.',
    keyIdeas:[],
    keyWorks:[],
    sections:[{heading:'',paragraphs:[
      'Thomas Nagel asks what increasingly objective understanding gains and what it can leave out. “What Is It Like to Be a Bat?” argues that a conscious organism has a subjective character: there is something it is like to be that organism. Objective knowledge of echolocation, behavior, and physiology can be extensive without reproducing the bat’s point of view. The challenge is not that bats are unknowable, science is useless, or consciousness must be an immaterial soul. It is that a theory of mind must explain how first-person character belongs to the natural world.',
      'The View from Nowhere generalizes this tension. Each person lives through particular projects, attachments, and vulnerabilities while also recognizing themselves as one person among others. The impersonal standpoint supports altruistic reasons, self-criticism, and equality, but cannot simply erase personal life. Moral luck exposes how responsibility depends on outcomes, circumstances, character, and opportunities outside control. “War and Massacre” defends agent-centered constraints even under public pressure for better aggregate results. Equality and Partiality asks how legitimate institutions can reconcile equal concern with citizens who retain partial commitments; his state-centered account of global justice remains strongly contested.',
      'Mind and Cosmos later extends anti-reductionism into a speculative philosophy of nature. Nagel argues that consciousness, reason, and value require explanation and canvasses psychophysical and teleological possibilities while rejecting theism and intelligent design. These are proposed possibilities, not established science, and critics argue that the book underestimates evolutionary explanation and supplies no testable mechanism. Its claims should not be projected backward as the meaning of the bat essay. Nagel’s continuing project is wider: death as deprivation, absurdity, reasons, rationalism, equality, legitimacy, and the uneasy coexistence of perspectives.',
    ]}],
    presentation:{mode:'concise',orientation:[
      {label:'Central tension',value:'Subjective experience and increasingly objective understanding'},
      {label:'Ethical standpoints',value:'Personal reasons · altruism · moral luck · constraint'},
      {label:'Political questions',value:'Equality · partiality · legitimacy · global justice'},
      {label:'Later controversy',value:'Mind and Cosmos proposes disputed natural teleology'},
      {label:'Interpretive limit',value:'The bat argument is neither unknowability nor a proof of dualism'},
    ],articleActionLabel:'Read the full sourced Thomas Nagel article',bodyLayout:'prose',plaqueKicker:'',plaqueSubtitleLines:4},
    objectInterpretations:objectInterpretations([
      ['thomas-nagel-portrait','The 1978 portrait identifies Nagel at a particular career moment but cannot display another subject’s experience or settle the relation between subjective and objective standpoints.'],
      ['thomas-nagel-teaching','The 2008 classroom photograph documents Nagel teaching; it is not evidence for the 1974 bat argument, his political conclusions, or the speculative proposals in Mind and Cosmos.'],
    ]),
  },
  'derek-parfit':{
    lead:'Derek Parfit asks whether numerical identity is the further fact that makes survival, responsibility, and concern for the future matter.',keyIdeas:[],keyWorks:[],
    sections:[{heading:'',paragraphs:[
      'Derek Parfit asks whether numerical identity is the further fact that makes survival, responsibility, and concern for the future matter. In Reasons and Persons, Relation R joins psychological connectedness—direct links of memory, intention, and desire—with continuity formed by overlapping chains. These relations can vary by degree even though identity cannot be partial. Branching shows the distinction: two successors might each continue one earlier psychology although neither can be numerically identical with the one earlier person. The science-fiction cases isolate a conceptual argument; they are not predictions that technology will dissolve the self.',
      'The same book tests self-interest, morality, future generations, and population principles. The non-identity problem arises when a choice affects which people will exist: a harmful policy may leave future people with worthwhile lives who could not have existed under the alternative. Population ethics then produces conflicts among plausible principles, including the Repugnant Conclusion. Parfit exposed that conclusion as a problem; he did not simply recommend creating the largest population with lives barely worth living.',
      'On What Matters advances a later project about objective reasons and possible convergence. Its Triple Theory reconstructs Kantian, Scanlonian, and rule-consequentialist principles so their best versions may permit the same acts. This is not a historical claim that the traditions always agreed, and the later volumes contain revisions and replies rather than a victory declaration. Critics dispute the revisions, demandingness, aggregation, and Parfit’s non-naturalist normativity. The All Souls image locates his intellectual life but does not represent Relation R, future persons, or agreement among theories.',
    ]}],presentation:{mode:'concise',orientation:[{label:'Identity',value:'Relation R · connectedness · continuity · reductionism'},{label:'Survival',value:'What matters can remain when identity does not'},{label:'Future ethics',value:'Non-identity · population principles · future generations'},{label:'Later project',value:'Objective reasons · Triple Theory · convergence'},{label:'Open disputes',value:'Normativity · demandingness · aggregation · personal concern'}],articleActionLabel:'Read the full sourced Derek Parfit article',bodyLayout:'prose',plaqueKicker:'',plaqueSubtitleLines:4},
    objectInterpretations:objectInterpretations([['moral-parfit-all-souls-college','The All Souls photograph identifies an institutional setting associated with Parfit, not an image of Relation R or evidence that his disputed conclusions are true.']]),
  },
  'martha-nussbaum':{
    lead:'Martha Nussbaum asks which real opportunities people require to live with dignity, and how vulnerable lives can be supported without imposing one compulsory form of flourishing.',keyIdeas:[],keyWorks:[],
    sections:[{heading:'',paragraphs:[
      'Martha Nussbaum asks which real opportunities people require to live with dignity. A capability is a genuine opportunity to achieve a functioning, while a functioning is the achieved being or doing. Resources alone do not reveal what differently situated people can actually do with them. Her political version proposes a revisable list of central capabilities and a threshold each person should reach while normally preserving adult choice about exercise. Amartya Sen’s related approach emphasizes comparative assessment and public reasoning without one canonical list. The shared history should not be compressed into a sole-founder story.',
      'The Fragility of Goodness and Upheavals of Thought connect practical reason to tragedy, attachment, luck, and emotions understood as evaluative appraisals. Literature can educate attention to particulars and unfamiliar lives, while public emotions can sustain or deform democracy in concrete institutional settings. Nussbaum’s advocacy and commentary draw on this philosophy but remain different genres from a book-length argument.',
      'Frontiers of Justice extends the inquiry to disability, global inequality, and nonhuman animals, challenging contract models centered on independent citizens bargaining for mutual advantage. Dependency and care are political facts, not departures from an otherwise self-sufficient human norm. Critics question universalism, paternalism, cultural authority, measurement, institutional assignment, and political implementation. Nussbaum answers that dignity requires cross-cultural minima while capabilities protect plural choice. Political liberalism is meant to avoid a comprehensive doctrine of the good, though critics dispute whether the list succeeds in doing so. The portrait identifies the philosopher; it cannot visualize, measure, or settle a capability threshold.',
    ]}],presentation:{mode:'concise',orientation:[{label:'Core distinction',value:'Capabilities are opportunities; functionings are achievements'},{label:'Political proposal',value:'Dignity · central list · thresholds · plural choice'},{label:'Wider corpus',value:'Tragedy · emotion · literature · democratic education'},{label:'Frontiers',value:'Disability · global justice · nonhuman animals'},{label:'Open disputes',value:'Universalism · paternalism · measurement · institutions'}],articleActionLabel:'Read the full sourced Martha Nussbaum article',bodyLayout:'prose',plaqueKicker:'',plaqueSubtitleLines:4},
    objectInterpretations:objectInterpretations([['martha-nussbaum-portrait-2010','The portrait identifies Nussbaum at one moment; it does not represent a central capability, establish a threshold, or collapse her work into public advocacy.']]),
  },
  'judith-butler':{
    lead:'Judith Butler asks how reiterative norms make bodies, genders, and lives recognizable—and how embodied action can contest those norms.',keyIdeas:[],keyWorks:[],
    sections:[{heading:'',paragraphs:[
      'Judith Butler asks how reiterative norms make bodies, genders, and lives recognizable. Performativity is not voluntary theater: subjects act within conventions that precede them, and repetition can both stabilize and expose those conventions. No single performance creates a gender outside history, yet repetition is never perfectly closed to political variation. Bodies That Matter clarifies that construction is a process of materialization under power, not a denial that bodies, pain, dependency, or material limits are real.',
      'Giving an Account of Oneself turns toward ethical relation. Because no one is fully transparent about the social conditions of becoming a self, responsibility cannot require a complete self-originating story. Opacity can temper punitive judgment without licensing evasion of accountability. Precarious Life and Frames of War ask why some lives become publicly grievable while others are framed as unreal. Kinship, recognition, Jewish ethics, and Israel/Palestine enter distinct arguments whose controversies should not replace explanation of the philosophy. These later concerns widen rather than erase the early analysis of norms.',
      'Notes Toward a Performative Theory of Assembly treats gathered bodies as claims about livability, infrastructure, and who counts as the people. Appearance depends on food, shelter, transport, media, care, and exposure to policing; bodily gathering is not imagined to transform material conditions by gesture alone. The Force of Nonviolence later grounds an active nonviolence in interdependency and equal grievability. Critics contest Butler’s accounts of sex, language, violence, and political application. The portrait identifies Butler but cannot display performativity, settle public disputes, or represent the changes across this corpus.',
    ]}],presentation:{mode:'concise',orientation:[{label:'Performativity',value:'Reiterative norms, not voluntary theatrical choice'},{label:'Materialization',value:'Bodies are real and socially formed under constraint'},{label:'Ethical relation',value:'Opacity · responsibility · recognition · vulnerability'},{label:'Political development',value:'Grievability · assembly · interdependency · nonviolence'},{label:'Open disputes',value:'Sex · language · violence · Israel/Palestine · application'}],articleActionLabel:'Read the full sourced Judith Butler article',bodyLayout:'prose',plaqueKicker:'',plaqueSubtitleLines:4},
    objectInterpretations:objectInterpretations([['feminist-butler-portrait','The portrait identifies Butler; it does not depict a performative act, prove a theory of materialization, or adjudicate later political controversy.']]),
  },
  'angela-davis':{
    lead:'',keyIdeas:[],keyWorks:[],
    sections:[{heading:'',paragraphs:[
      'Angela Davis treats freedom as a collective institutional project rather than a private possession. The prison-industrial complex names more than private prison profit: punishment, racial hierarchy, policing, political incentives, labor, media, and withdrawn social provision can reinforce one another. Public institutions and political habits remain central even where no private operator is present. Are Prisons Obsolete? asks why incarceration appears inevitable, which histories it conceals, and why reforms can sometimes enlarge the system they promise to improve. The framework therefore asks how punishment becomes common sense, whose security it protects, and which social needs a carceral response leaves unmet.',
      'Abolition Democracy makes abolition constructive as well as negative. Closing institutions without building education, housing, health, democratic participation, conflict response, and accountability would leave the conditions of harm intact. Davis offers a direction and criteria for non-reformist change, not one completed institutional blueprint. Women, Race & Class reconstructs conflicts among slavery, suffrage, labor, racism, and feminism; Blues Legacies and Black Feminism analyzes cultural expression; Freedom Is a Constant Struggle gathers international speeches and interviews. These genres are not interchangeable treatises. Historical reconstruction, cultural criticism, autobiography, and movement address each make different evidentiary demands and reveal different parts of her political method.',
      'Davis’s Communist affiliations, 1972 acquittal, academic life, and international organizing matter, but biography cannot substitute for her arguments. International solidarity compares struggles without making their histories identical. Collective struggle also resists turning freedom into the achievement of one heroic individual. Critics press abolition about severe violence, transition, state power, alliance, and feasibility; later movements extend rather than simply repeat Davis. The displayed photograph documents Davis speaking at a university theatre in 2006. It identifies a lifetime public role, but it neither records the subject of that talk nor depicts an institutional alternative or proves a political claim.',
    ]}],presentation:{mode:'concise',orientation:[
      {heading:'Key ideas',items:[
        {label:'Constructive abolition',description:'Freedom requires dismantling carceral systems while building education, housing, health, accountability, and democratic ways of responding to harm.'},
        {label:'Prison-industrial complex',description:'A name for linked institutions, incentives, racial hierarchies, labor arrangements, media habits, and political choices—not only private prisons.'},
      ]},
      {heading:'Works and methods',items:[
        {label:'Women, Race & Class',description:'A historical argument tracing conflicts among slavery, labor, suffrage, racism, and feminist organizing.'},
        {label:'A varied corpus',description:'Books, cultural studies, autobiography, interviews, and speeches address different audiences and should not be read as one interchangeable treatise.'},
      ]},
      {heading:'Continuing questions',items:[
        {label:'Reform and transition',description:'Which changes reduce carceral power, and which apparently humane reforms make incarceration more durable or expansive?'},
        {label:'Coalition and solidarity',description:'Collective struggle can connect movements across borders without pretending their histories, risks, or political demands are identical.'},
      ]},
    ],articleActionLabel:'Read the full sourced Angela Davis article',bodyLayout:'prose',exhibitLayout:'object-led',plaqueKicker:'',plaqueSubtitleLines:4},
    objectInterpretations:objectInterpretations([['colonial-davis-portrait','This uncropped 2006 photograph shows Angela Davis speaking at the Myer Horowitz Theatre at the University of Alberta. It documents her likeness and a lifetime public appearance, but the source does not identify the talk’s subject; the image cannot represent constructive abolition, establish a political association, or substitute for the arguments in her books.']]),
    sources:[
      {label:'Angela Y. Davis — Blues Legacies and Black Feminism',url:'https://www.penguinrandomhouse.com/books/36908/blues-legacies-and-black-feminism-by-angela-y-davis/',kind:'primary-text'},
      {label:'Angela Y. Davis — Freedom Is a Constant Struggle',url:'https://www.haymarketbooks.org/books/780-freedom-is-a-constant-struggle',kind:'primary-text'},
      {label:'Angela Y. Davis — Angela Davis: An Autobiography',url:'https://www.penguinrandomhouse.com/books/36907/angela-davis-an-autobiography-by-angela-y-davis/',kind:'primary-text'},
      {label:'Joanna M. Latimer — Angela Davis and the Work of Freedom',url:'https://doi.org/10.1086/729280',kind:'academic-reference'},
      {label:'Donna Murch — The AAUP and the Angela Davis Case',url:'https://www.aaup.org/academe/issues/spring-2024/aaup-and-angela-davis-case',kind:'academic-reference'},
    ],
    review:{status:'standard-compliant',reviewedOn:'2026-08-09',method:'Reconciled against the current claim-reviewed article, registered interpretation sources, and the verified principal-object record; caption, rights, alt text, full-composition preview, object-led presentation, and subject-specific visitor guide reviewed against the locked exhibit standard.',lock:'fnv1a64:3ed83fd895f78029'},
  },
  'bell-hooks':{
    lead:'',keyIdeas:[],keyWorks:[],
    sections:[{heading:'',paragraphs:[
      'bell hooks defines feminism as a movement to end sexist oppression rather than a path for a privileged group of women to gain equal access within domination. Feminist Theory: From Margin to Center criticizes white, middle-class universalization and analyzes race, class, gender, and imperialism together. The margin is a standpoint from which structures hidden by the center can become legible, not a romantic name for deprivation. This overlaps later intersectional analysis, but Kimberlé Crenshaw introduced the term “intersectionality” in a distinct 1989 legal argument; hooks’s earlier vocabulary and method should remain visible. Her accessible style is part of a public intellectual practice, not evidence that the arguments are simple or uncontested.',
      'Teaching to Transgress presents engaged pedagogy as a practice of freedom that joins critical consciousness, voice, embodiment, preparation, and responsibility. Students are participants rather than passive containers, but teachers still structure inquiry and answer for unequal classroom conditions. Black Looks studies representation and the oppositional gaze, asking how spectators can refuse images that naturalize domination. The Will to Change examines how patriarchy wounds men while preserving male power. Neither experience nor accessibility places an argument beyond criticism; classrooms, family, religion, and popular culture remain contested sites where authority and resistance must both be examined.',
      'All About Love defines love as an ethical practice involving care, commitment, knowledge, responsibility, respect, and trust. Beloved community connects intimate transformation with collective life rather than retreating from politics. The ethical vocabulary challenges domination in households and movements while leaving questions about coercive institutions and material redistribution open. Critics question essentialism, spiritual language, institutional strategy, and broad cultural generalizations. The lowercase authorial name is preserved. The displayed 2009 photograph shows hooks holding a microphone as she speaks, but its source names no venue or event. It identifies her without documenting a classroom, a particular lecture, engaged pedagogy, beloved community, or the full range of her corpus.',
    ]}],presentation:{mode:'concise',orientation:[
      {heading:'Key ideas',items:[
        {label:'Feminism from margin to center',description:'Feminism is a mass movement against sexist oppression, not equal access for a privileged few within unchanged structures of domination.'},
        {label:'Interlocking domination',description:'Race, class, gender, and imperial power shape one another; this vocabulary overlaps later intersectionality without originating Crenshaw’s distinct term.'},
      ]},
      {heading:'Education and culture',items:[
        {label:'Engaged pedagogy',description:'Students bring experience and voice into critical inquiry while teachers remain responsible for preparation, structure, and unequal classroom power.'},
        {label:'Oppositional gaze',description:'Critical spectatorship can challenge images that make racial and gendered domination appear natural, desirable, or invisible.'},
      ]},
      {heading:'Ethics and debate',items:[
        {label:'Love and beloved community',description:'Care, commitment, knowledge, responsibility, respect, and trust connect intimate transformation to collective freedom rather than replacing politics.'},
        {label:'Continuing disputes',description:'Readers debate essentialism, spiritual language, classroom authority, broad cultural claims, material redistribution, and the institutional reach of her ethics.'},
      ]},
    ],articleActionLabel:'Read the full sourced bell hooks article',bodyLayout:'prose',exhibitLayout:'object-led',plaqueKicker:'',plaqueSubtitleLines:4},
    objectInterpretations:objectInterpretations([['colonial-hooks-portrait','This uncropped 2009 lifetime photograph shows bell hooks holding a microphone and gesturing as she speaks. The source identifies neither venue nor event, so the image documents her likeness and public speaking without establishing a particular lecture, classroom, or political action; it cannot itself depict engaged pedagogy, beloved community, or the arguments of her books.']]),
    sources:[
      {label:'bell hooks — All About Love',url:'https://www.harpercollins.com/products/all-about-love-bell-hooks',kind:'primary-text'},
      {label:'bell hooks — The Will to Change',url:'https://www.simonandschuster.com/books/The-Will-to-Change/bell-hooks/9780743456081',kind:'primary-text'},
      {label:'Kimberlé Crenshaw — Demarginalizing the Intersection of Race and Sex',url:'https://chicagounbound.uchicago.edu/uclf/vol1989/iss1/8/',kind:'primary-text'},
      {label:'Namulundah Florence — bell hooks’ Engaged Pedagogy',url:'https://books.google.com/books/about/Bell_Hooks_Engaged_Pedagogy.html?id=ecvWAAAAMAAJ',kind:'academic-reference'},
    ],
    review:{status:'standard-compliant',reviewedOn:'2026-08-09',method:'Reconciled against the current claim-reviewed article, registered interpretation sources, and the verified principal-object record; caption, rights, alt text, full-composition preview, object-led presentation, and subject-specific visitor guide reviewed against the locked exhibit standard.',lock:'fnv1a64:149d736da759628b'},
  },
};
