import type {MuseumSupplementalExhibit} from './platoSupplementalExhibits';

type ReviewEvidence = {
  plaqueTitle: string;
  invitation: string;
  plaqueType: NonNullable<MuseumSupplementalExhibit['wallPlaque']>['type'];
  canonicalContexts: NonNullable<MuseumSupplementalExhibit['wallPlaque']>['canonicalContexts'];
  articleTitle: string;
  objectInterpretation: string;
  paragraphs: readonly [string, string, string];
  paragraphSourceIds: readonly [readonly string[], readonly string[], readonly string[]];
  sources: MuseumSupplementalExhibit['sources'];
  visitorGuide: NonNullable<MuseumSupplementalExhibit['visitorGuide']>;
  resolution: string;
  lock: string;
  overrides?: Partial<Pick<MuseumSupplementalExhibit,
    | 'displayName'
    | 'shortTitle'
    | 'workLabel'
    | 'dateLabel'
    | 'question'
    | 'frontSubtitle'
    | 'lead'
  >>;
};

const collection = (id: string, label: string, url: string) => ({id, label, url, kind: 'collection-record' as const});
const academic = (id: string, label: string, url: string) => ({id, label, url, kind: 'academic-reference' as const});
const primary = (id: string, label: string, url: string) => ({id, label, url, kind: 'primary-text' as const});

const evidence: Record<string, ReviewEvidence> = {
  'descartes-discourse-method': {
    plaqueTitle: 'Rainbow Diagram from Les Météores',
    plaqueType: 'concept-argument-diagram-or-method',
    canonicalContexts: [{kind: 'philosopher', id: 'descartes'}],
    articleTitle: 'René Descartes',
    invitation: 'Printed with the Discourse’s scientific essays in 1637, this ray diagram makes Descartes’s method visible as geometrical reasoning tested against an observed phenomenon.',
    objectInterpretation: 'The installed landscape image is Descartes’s 1637 diagram of rainbow formation from Les Météores, not the Discourse title page named by its legacy asset identifier. Rays enter and leave a spherical drop to model refraction and reflection. The supplied reproduction does not identify a holding institution or particular printed copy.',
    overrides: {
      displayName: 'Rainbow Diagram from Les Météores',
      shortTitle: 'Descartes’s Rainbow Diagram',
      workLabel: 'SCIENTIFIC DIAGRAM · RAINBOW FORMATION',
      dateLabel: 'René Descartes · Leiden, 1637 · exemplar unrecorded',
      frontSubtitle: 'Geometry, refraction, observation, and the scientific essays beside the Discourse',
      lead: 'Descartes’s ray diagram belongs to the meteorological essay published with the Discourse on Method. It shows method at work through a constructed optical model, not reason operating without observation.',
    },
    paragraphs: [
      'The installed object is a landscape diagram in which rays cross a spherical water drop, bend at its surfaces, and return toward an observer. The Commons record identifies it with René Descartes’s account of rainbow formation published in 1637; the derivative preserves the entire diagram at its natural ratio. It is not the title page of the Discourse, despite the obsolete asset name that once described it. Nor does the source record identify a library, shelfmark, or individual printed exemplar. The image can therefore establish the form and subject of a historical optical diagram, but not a complete copy-level provenance or every detail of workshop responsibility for the reproduction.',
      'The Discourse appeared as an introduction to essays on optics, meteorology, and geometry. That publication design matters: Descartes’s four rules do not function as an automatic recipe detached from practice. In the rainbow inquiry, geometrical construction works alongside observations of color, artificial droplets, refraction, and prior optical work. A model selects relevant features and reasons from them; its success still depends on whether the construction organizes appearances convincingly. Descartes’s mathematical natural philosophy consequently joined deduction, hypothesis, experiment, and judgment in ways obscured by the slogan that rationalists simply ignored experience.',
      'Methodical order asks an inquirer to withhold premature assent, divide difficult questions, proceed from manageable dependencies, and review the chain. Yet the diagram exposes choices the rules cannot make mechanically: which mechanism to isolate, which simplification is legitimate, and what counts as agreement between geometry and a changing natural event. It also places vernacular philosophical autobiography beside technically demanding essays intended to demonstrate intellectual authority. The object thus supports a bounded claim. Descartes proposed a disciplined and portable way to direct inquiry, but the historical demonstration required material phenomena and crafted representations rather than certainty generated by pure introspection alone.',
    ],
    paragraphSourceIds: [['rainbow-commons'], ['descartes-sep', 'discourse-primary'], ['descartes-sep', 'discourse-primary']],
    sources: [
      collection('rainbow-commons', 'Wikimedia Commons — Descartes rainbow-formation diagram, 1637', 'https://commons.wikimedia.org/wiki/File:Descartes_Rainbow.png'),
      primary('discourse-primary', 'René Descartes — Discourse on Method, Project Gutenberg', 'https://www.gutenberg.org/ebooks/59'),
      academic('descartes-sep', 'Stanford Encyclopedia of Philosophy — René Descartes', 'https://plato.stanford.edu/entries/descartes/'),
    ],
    visitorGuide: [
      {heading: 'Reading the optical model', items: [
        {label: 'Refraction', description: 'A ray changes direction at a boundary; the diagram turns that relation into a geometrical path.', sourceIds: ['rainbow-commons', 'descartes-sep']},
        {label: 'A spherical drop', description: 'The circle is a model of a water drop, not a map of the sky or a title-page ornament.', sourceIds: ['rainbow-commons']},
      ]},
      {heading: 'Testing method', items: [
        {label: 'Constructed evidence', description: 'Geometry organizes observation, but judgment still selects the model and tests its fit.', sourceIds: ['descartes-sep', 'discourse-primary']},
        {label: 'Essays beside the Discourse', description: 'Optics, meteorology, and geometry demonstrate method through scientific problems published with the 1637 text.', sourceIds: ['descartes-sep', 'discourse-primary']},
      ]},
    ],
    resolution: 'Resolved: reconciled the installed 1637 rainbow diagram against the false title-page identifier, bounded its unrecorded exemplar provenance, replaced the portrait mount with the live landscape ratio, mapped claims to object, primary, and scholarly sources, and linked the current René Descartes article.',
    lock: 'fnv1a64:579b5da5410ef3bf',
  },
  'descartes-meditations-foundation': {
    plaqueTitle: 'Meditations on First Philosophy (1641)',
    plaqueType: 'work-or-text',
    canonicalContexts: [{kind: 'philosopher', id: 'descartes'}],
    articleTitle: 'René Descartes',
    invitation: 'The 1641 Latin title page introduces a work that radicalizes doubt, locates certainty in present thinking, and makes objections part of its published argument.',
    objectInterpretation: 'The installed object is the title page of the first Latin edition of Descartes’s Meditationes de prima philosophia, printed by Michel Soly in Paris in 1641 and reproduced through the BnF/Gallica record. It establishes publication context, not an autograph manuscript or proof of a particular interpretation.',
    overrides: {
      displayName: 'Meditations on First Philosophy (1641)',
      shortTitle: 'The First Latin Meditations',
      workLabel: 'FIRST LATIN EDITION · TITLE PAGE',
      dateLabel: 'René Descartes · Paris, 1641 · Michel Soly',
      frontSubtitle: 'Doubt, present thinking, recovery, embodiment, and published objection',
    },
    paragraphs: [
      'Dense Latin type fills the installed title page of Meditationes de prima philosophia, printed by Michel Soly in Paris in 1641. It announces Descartes’s demonstrations concerning God and the distinction of soul from body and belongs to the first Latin edition preserved through the Bibliothèque nationale de France and Gallica source chain. The natural portrait ratio keeps the complete page visible, including its typographic hierarchy and imprint. This is printed paratext rather than Descartes’s handwriting. It securely situates the book’s initial publication, but a title page cannot by itself establish how the six meditations argue, whether their demonstrations succeed, or how later readers should resolve their disputes.',
      'The work deliberately escalates uncertainty. Ordinary sensory mistakes give way to dreaming, then to a deceiver capable of undermining even familiar reasoning. In that performance, the meditator discovers that the present act of thinking cannot be separated from existence while it occurs. The cogito is therefore not merely a general syllogism read from the page. Descartes then attempts a much harder recovery through clear and distinct perception, arguments for a non-deceiving God, the external world, and the real distinction of mind and body. Each transition bears argumentative burdens that critics have contested, including the alleged Cartesian Circle and the status of the thinking self.',
      'Publication made that contest structural rather than accidental. Sets of objections from figures including Caterus, Mersenne’s circle, Hobbes, Arnauld, and Gassendi appeared with Descartes’s replies, and the expanded 1642 edition added more material. The resulting work models philosophy as staged meditation and public dispute. Its account of distinct substances also does not cancel the human being’s experienced union of mind and body, a problem pressed forcefully by Elisabeth of the Palatinate. The linked article follows those arguments and tensions. The title page remains valuable as material evidence that foundational ambition entered print together with named theses, institutional networks, and organized criticism.',
    ],
    paragraphSourceIds: [['meditations-commons'], ['meditations-primary', 'descartes-epistemology'], ['descartes-sep', 'meditations-primary']],
    sources: [
      collection('meditations-commons', 'Bibliothèque nationale de France / Wikimedia Commons — 1641 Meditations title page', 'https://commons.wikimedia.org/wiki/File:Meditationes_de_prima_philosophia_1641.jpg'),
      primary('meditations-primary', 'René Descartes — Meditations on First Philosophy, Project Gutenberg', 'https://www.gutenberg.org/ebooks/23306'),
      academic('descartes-epistemology', 'Stanford Encyclopedia of Philosophy — Descartes’s Epistemology', 'https://plato.stanford.edu/entries/descartes-epistemology/'),
      academic('descartes-sep', 'Stanford Encyclopedia of Philosophy — René Descartes', 'https://plato.stanford.edu/entries/descartes/'),
    ],
    visitorGuide: [
      {heading: 'Following the meditation', items: [
        {label: 'Methodical doubt', description: 'The skeptical scenarios are a temporary investigative practice, not Descartes’s settled conclusion.', sourceIds: ['meditations-primary', 'descartes-epistemology']},
        {label: 'Cogito', description: 'Present thinking supplies certainty while enacted, though what kind of self it establishes remains disputed.', sourceIds: ['meditations-primary', 'descartes-epistemology']},
      ]},
      {heading: 'Testing the recovery', items: [
        {label: 'Clear and distinct perception', description: 'Its epistemic role belongs inside Descartes’s larger argument about divine non-deception.', sourceIds: ['descartes-epistemology']},
        {label: 'Objections and replies', description: 'Published criticism is part of the work’s historical architecture, not an optional modern appendix.', sourceIds: ['meditations-primary', 'descartes-sep']},
      ]},
    ],
    resolution: 'Resolved: verified the installed 1641 Paris title page, preserved its BnF publication provenance and public-domain status, separated paratext from philosophical proof, corrected the mount to its natural portrait ratio, sourced all three claim paragraphs, and linked the current René Descartes article.',
    lock: 'fnv1a64:a07b6f948f9f3489',
  },
  'elisabeth-descartes-union': {
    plaqueTitle: 'Elisabeth of the Palatinate',
    plaqueType: 'paired-or-grouped-historical-figures',
    canonicalContexts: [{kind: 'philosopher', id: 'descartes'}],
    articleTitle: 'René Descartes',
    invitation: 'Cooper’s miniature introduces the philosopher whose letters pressed Descartes to explain how an unextended mind could act with an extended body.',
    objectInterpretation: 'The installed object is Alexander Cooper’s c. 1640–1650 portrait miniature of Elisabeth of the Palatinate, after Gerrit van Honthorst, Rijksmuseum SK-A-4314. Formerly misidentified as Henrietta Maria, it depicts Elisabeth but does not depict or authenticate her correspondence.',
    overrides: {
      displayName: 'Elisabeth of the Palatinate',
      shortTitle: 'Elisabeth’s Challenge',
      workLabel: 'PORTRAIT MINIATURE · PHILOSOPHY IN LETTERS',
      dateLabel: 'Alexander Cooper, after Gerrit van Honthorst · c. 1640–1650 · Rijksmuseum',
      frontSubtitle: 'Causation, embodiment, passions, health, freedom, and philosophical exchange',
    },
    paragraphs: [
      'Alexander Cooper’s small portrait presents Elisabeth of the Palatinate in a dark dress, lace collar, and pearls. The Rijksmuseum identifies the work as a miniature made around 1640–1650 after a portrait by Gerrit van Honthorst, inventory SK-A-4314, and records that the sitter was formerly misidentified as Henrietta Maria. That correction matters because images inherit catalog histories as well as appearances. The installed derivative preserves the portrait at its natural ratio and carries the collection’s open-use status. It does not show a letter, a philosophical conversation, or a transparent inner life. Its role is to restore a historically specific face to an argument preserved elsewhere in texts.',
      'Beginning in 1643, Elisabeth asks Descartes how a thinking substance, defined as unextended, can determine bodily spirits to act. The question is not a novice’s request for repetition. It identifies pressure between causal explanation and the real distinction asserted in the Meditations, and it prompts Descartes to emphasize the primitive notion of mind-body union. Their exchange extends into the passions, health, freedom, virtue, and the practical difficulty of governing attention under illness and political strain. Elisabeth proposes examples, objections, and standards of intelligibility of her own; treating her merely as Descartes’s muse or pupil erases the philosophical agency visible in the correspondence.',
      'Letters make the setting and survival of the philosophy consequential. Elisabeth could participate in learned networks but not simply enter the institutions available to many male scholars. The surviving exchange is also mediated: copies, editorial selection, and later publication shape what readers possess. Descartes’s account of the passions attempts to join bodily mechanisms with reasons, judgments, habits, and the lived unity of a person, while Elisabeth keeps asking whether the explanatory pieces genuinely meet. The miniature cannot settle that interaction problem. It can instead interrupt a solitary-genius story and direct visitors toward a philosophy formed through challenge, reply, revision, and unequal but intellectually substantive correspondence.',
    ],
    paragraphSourceIds: [['elisabeth-commons'], ['elisabeth-sep', 'passions-sep'], ['elisabeth-sep', 'passions-sep']],
    sources: [
      collection('elisabeth-commons', 'Rijksmuseum / Wikimedia Commons — portrait miniature of Elisabeth of the Palatinate', 'https://commons.wikimedia.org/wiki/File:Elizabeth_(1618-80)_van_de_Paltz,_dochter_van_Frederik_V,_koning_van_Bohemen,_bijgenaamd_de_%27Winterkoning%27_Rijksmuseum_SK-A-4314.jpeg'),
      academic('elisabeth-sep', 'Stanford Encyclopedia of Philosophy — Elisabeth, Princess of Bohemia', 'https://plato.stanford.edu/entries/elisabeth-bohemia/'),
      academic('passions-sep', 'Stanford Encyclopedia of Philosophy archive — Descartes on the emotions', 'https://plato.stanford.edu/entries/emotions-17th18th/LD2Descartes.html'),
    ],
    visitorGuide: [
      {heading: 'Following Elisabeth’s argument', items: [
        {label: 'Interaction problem', description: 'Elisabeth asks what intelligible causal relation could connect unextended thought and extended body.', sourceIds: ['elisabeth-sep']},
        {label: 'Primitive union', description: 'Descartes replies that lived mind-body union is known differently from thought or extension considered alone.', sourceIds: ['elisabeth-sep', 'passions-sep']},
      ]},
      {heading: 'Reading philosophy in letters', items: [
        {label: 'Independent agency', description: 'Elisabeth frames objections and develops positions on passions, health, virtue, and freedom.', sourceIds: ['elisabeth-sep']},
        {label: 'Mediated survival', description: 'Copied and edited letters preserve an exchange without giving readers a simple, complete autograph archive.', sourceIds: ['elisabeth-sep']},
      ]},
    ],
    resolution: 'Resolved: verified Cooper’s Rijksmuseum miniature and its corrected sitter identification, avoided treating a portrait as correspondence evidence, restored Elisabeth’s philosophical agency, preserved the transmission limit, mounted the object naturally, and linked the current René Descartes article.',
    lock: 'fnv1a64:db5c435b81067e5a',
  },
  'descartes-treatise-man-embodiment': {
    plaqueTitle: 'Diagram Associated with Treatise of Man',
    plaqueType: 'concept-argument-diagram-or-method',
    canonicalContexts: [{kind: 'philosopher', id: 'descartes'}],
    articleTitle: 'René Descartes',
    invitation: 'This historically transmitted diagram stages sensory pathways and pineal mediation in Descartes’s mechanical physiology while leaving its exact plate history unresolved.',
    objectInterpretation: 'The installed object is a historical diagram associated with Descartes’s Treatise of Man. Its source shows sensory pathways and pineal mediation, but the supplied modern reproduction does not establish the exact original plate, designer, edition, or publication date. It is not a modern neural map or a securely author-drawn sheet.',
    overrides: {
      displayName: 'Diagram Associated with Treatise of Man',
      shortTitle: 'Descartes’s Physiological Model',
      workLabel: 'HISTORICAL DIAGRAM · SENSATION AND MEDIATION',
      dateLabel: 'Associated with Treatise of Man · exact plate and edition unresolved',
      frontSubtitle: 'Nerves, animal spirits, pineal mediation, mechanism, and lived union',
      lead: 'A transmitted physiological diagram visualizes causal pathways in Descartes’s mechanistic account. Its bibliographic identity is incomplete, so the image supports analysis of a model without becoming a securely dated authorial drawing.',
    },
    paragraphs: [
      'Lines run from stimulated sense organs through a cutaway head toward a central point in the installed physiological diagram. The Commons reproduction associates the image with Descartes and Treatise of Man, but its citation through a modern Cambridge edition does not identify the original plate, illustrator, first printing, or shelfmark. The scene and panel derivatives preserve the full portrait composition at the live image ratio. Because transmission details are incomplete, the safest identification is a diagram associated with the work. Calling it Descartes’s own drawing, a securely dated manuscript, or a modern anatomical cross-section would turn a useful but bounded reproduction into evidence it does not supply.',
      'Treatise of Man develops a mechanistic model of bodily functions: external motions affect sense organs, nerves and animal spirits transmit changes, and bodily structures coordinate response without requiring a rational soul at each step. The pineal gland receives a special mediating role in Descartes’s physiology, though later anatomy did not preserve that explanatory function. The French manuscript was not published in Descartes’s lifetime; editions appeared posthumously in the 1660s. “Machine” here belongs to a seventeenth-century explanatory program, not to contemporary neuroscience, and historical terms such as reflex must be used cautiously rather than projected backward as exact equivalents.',
      'Mechanism does not exhaust Descartes’s account of a human being. His dualism distinguishes thought from extension, yet his correspondence and Passions of the Soul also insist that embodied persons experience hunger, pain, emotion, and voluntary action through a genuine union. The diagram’s arrows can make interaction look easier than the metaphysics permits: a drawn path is not an explanation of how an unextended mind relates causally to extended matter. Elisabeth’s objections expose that gap. The object is strongest when read as a constructed physiological model with a history and limits, not as a master key that dissolves the problems of consciousness, agency, or embodiment.',
    ],
    paragraphSourceIds: [['treatise-diagram'], ['descartes-sep', 'pineal-sep'], ['descartes-sep', 'pineal-sep']],
    sources: [
      collection('treatise-diagram', 'Wikimedia Commons — diagram associated with Descartes’s Treatise of Man', 'https://commons.wikimedia.org/wiki/File:Descartes_diagram.png'),
      academic('descartes-sep', 'Stanford Encyclopedia of Philosophy — René Descartes', 'https://plato.stanford.edu/entries/descartes/'),
      academic('pineal-sep', 'Stanford Encyclopedia of Philosophy archive — Descartes and the Pineal Gland', 'https://plato.stanford.edu/archives/sum2026/entries/pineal-gland/'),
    ],
    visitorGuide: [
      {heading: 'Following the historical mechanism', items: [
        {label: 'Animal spirits', description: 'Fine bodily matter mediates motion in Descartes’s physiology; it is not a claim about immaterial ghosts.', sourceIds: ['descartes-sep', 'pineal-sep']},
        {label: 'Pineal mediation', description: 'Descartes assigns the gland a coordinating role that later anatomy did not retain.', sourceIds: ['pineal-sep']},
      ]},
      {heading: 'Respecting the model’s limits', items: [
        {label: 'Unresolved plate history', description: 'The supplied reproduction does not establish designer, original edition, or shelfmark.', sourceIds: ['treatise-diagram']},
        {label: 'Union exceeds a diagram', description: 'A drawn pathway does not by itself explain mind-body causation or lived embodiment.', sourceIds: ['descartes-sep', 'pineal-sep']},
      ]},
    ],
    resolution: 'Resolved: retained only the diagram identity supported by the installed reproduction, exposed the unresolved plate and edition history, replaced its severe landscape distortion with the live portrait ratio, kept historical mechanism distinct from modern neuroscience, and linked the current René Descartes article.',
    lock: 'fnv1a64:741d95fcd3933379',
  },
  'spinoza-ethics-geometrical-order': {
    plaqueTitle: 'Ethics, Part I Propositions (represented as 1677)',
    plaqueType: 'work-or-text',
    canonicalContexts: [{kind: 'philosopher', id: 'spinoza'}],
    articleTitle: 'Spinoza',
    invitation: 'This printed page places axioms and propositions in view while the Ethics asks whether geometrical order can clarify substance, necessity, affects, and human freedom.',
    objectInterpretation: 'The installed object is a typeset page represented by its source as Part I of Spinoza’s Ethics in the 1677 Opera posthuma, showing axioms and Propositions I–IV. The Commons record cites no holding institution or shelfmark, so it cannot establish a particular first-edition copy or an autograph manuscript.',
    overrides: {
      displayName: 'Ethics, Part I Propositions',
      shortTitle: 'Spinoza’s Geometrical Order',
      workLabel: 'PRINTED PAGE · AXIOMS AND PROPOSITIONS',
      dateLabel: 'Represented as Opera posthuma · 1677 · holding copy unrecorded',
      frontSubtitle: 'Definitions, axioms, demonstration, substance, necessity, affects, and freedom',
      lead: 'A printed Part I page shows the Ethics arranging claims as axioms, propositions, and demonstrations. Its source represents it as the 1677 Opera posthuma but supplies no repository or shelfmark, so edition-level certainty remains bounded.',
    },
    paragraphs: [
      'The installed landscape page contains the end of Part I’s axioms and the opening propositions of Ethica ordine geometrico demonstrata. Its Commons record represents the image as belonging to Spinoza’s posthumous Opera posthuma of 1677, and the visible typography agrees with a printed page rather than an autograph. The reproduction preserves that horizontal composition at its natural ratio. Yet the source points to no holding institution, shelfmark, or stable catalog record for a particular copy. It is therefore responsible to retain “represented as 1677” and the page-level identification while withholding stronger claims that this derivative verifies a unique first-edition exemplar or complete publication provenance.',
      'Geometrical order organizes the Ethics through definitions, axioms, propositions, demonstrations, corollaries, and scholia. The form makes dependencies inspectable, but it does not convert controversial premises into uncontroversial mathematics. In Part I, Spinoza argues for one substance, God or Nature, with finite things understood as modes; necessity follows from the nature of reality rather than from an external chooser who might have arranged it otherwise. Those claims depend on technical meanings of substance, attribute, mode, cause, and freedom. Readers disagree about how attributes relate to the intellect and about the precise character of Spinoza’s necessitarianism, so the page’s orderly surface should invite reconstruction rather than passive assent.',
      'The later parts move from metaphysics into mind, affects, bondage, reason, and blessedness. Freedom cannot mean exemption from causation in a necessitated world. It instead concerns becoming more active through adequate ideas, understanding the causes of affects, and participating more fully in the power of nature. That does not make emotions mere mistakes or promise complete self-mastery; bodies and social relations shape what a person can do. The geometrical presentation is thus both method and provocation: can a reader learn to see human life as intelligible without erasing vulnerability or responsibility? The linked article develops that system while the object keeps its printed architecture and provenance limit visible.',
    ],
    paragraphSourceIds: [['ethics-page'], ['ethics-primary', 'spinoza-sep'], ['ethics-primary', 'spinoza-sep']],
    sources: [
      collection('ethics-page', 'Wikimedia Commons — Ethics Part I page represented as Opera posthuma, 1677', 'https://commons.wikimedia.org/wiki/File:Spinoza_Ethica_Pars1_Prop1.jpg'),
      primary('ethics-primary', 'Baruch Spinoza — Ethics, Project Gutenberg', 'https://www.gutenberg.org/ebooks/3800'),
      academic('spinoza-sep', 'Stanford Encyclopedia of Philosophy — Baruch Spinoza', 'https://plato.stanford.edu/entries/spinoza/'),
    ],
    visitorGuide: [
      {heading: 'Reading geometrical order', items: [
        {label: 'Axioms and propositions', description: 'The page makes dependencies explicit; it does not guarantee that premises or demonstrations escape dispute.', sourceIds: ['ethics-page', 'ethics-primary']},
        {label: 'Substance, attribute, mode', description: 'Spinoza uses these terms technically to describe one reality and its finite expressions.', sourceIds: ['ethics-primary', 'spinoza-sep']},
      ]},
      {heading: 'Rethinking freedom', items: [
        {label: 'Necessity', description: 'Nothing falls outside nature’s causal order, but explanation distinguishes passive from more active life.', sourceIds: ['ethics-primary', 'spinoza-sep']},
        {label: 'Adequate ideas', description: 'Understanding causes can reorganize affects without promising disembodied or absolute control.', sourceIds: ['ethics-primary', 'spinoza-sep']},
      ]},
    ],
    resolution: 'Resolved: identified the printed Part I page without inventing a holding copy or shelfmark, qualified the 1677 source claim, restored its severe landscape-ratio defect, separated geometrical form from certainty, mapped all claims, and linked the current Spinoza article.',
    lock: 'fnv1a64:b6430e014b72d02c',
  },
  'spinoza-scripture-freedom': {
    plaqueTitle: 'Interior of the Portuguese Synagogue in Amsterdam',
    plaqueType: 'historical-event-or-institutional-context',
    canonicalContexts: [{kind: 'philosopher', id: 'spinoza'}],
    articleTitle: 'Spinoza',
    invitation: 'De Witte’s 1680 synagogue interior supplies later Amsterdam religious context for the Theological-Political Treatise; it does not depict Spinoza or his book.',
    objectInterpretation: 'The installed portrait-format object is Emanuel de Witte’s 1680 Interior of the Portuguese Synagogue in Amsterdam, Rijksmuseum SK-A-3738, not the Spinoza manuscript note named by its legacy identifier. The painting postdates both the synagogue’s 1675 opening and the 1670 Treatise and does not document Spinoza, his herem, or a textual page.',
    overrides: {
      displayName: 'Interior of the Portuguese Synagogue in Amsterdam',
      shortTitle: 'De Witte’s Synagogue Interior',
      workLabel: 'CONTEXT PAINTING · AMSTERDAM RELIGIOUS LIFE',
      dateLabel: 'Emanuel de Witte · 1680 · Rijksmuseum, SK-A-3738',
      frontSubtitle: 'A later institutional interior beside Spinoza’s arguments about interpretation and freedom',
      lead: 'Emanuel de Witte’s synagogue interior is a contextual painting, not a manuscript of the Theological-Political Treatise. Its later setting opens questions about public religion while the primary text supplies Spinoza’s arguments.',
    },
    paragraphs: [
      'Emanuel de Witte’s Interior of the Portuguese Synagogue in Amsterdam shows figures dispersed through the high, columned interior of the Esnoga. The Rijksmuseum dates the painting to 1680, five years after the building opened, and catalogs it as oil on canvas, SK-A-3738. The installed bytes and legacy acquisition manifest match that work, not a Spinoza manuscript. The museum record marks the object public domain, while the delivery file was registered as CC0; the Atlas preserves the source-chain distinction rather than silently upgrading rights. Most importantly, this later painting does not portray Spinoza, his 1656 exclusion, or the production of his anonymously published 1670 treatise.',
      'The Theological-Political Treatise argues that Scripture should be interpreted through language, historical circumstance, authorship, and the purposes of its communities rather than treated as a store of philosophical demonstrations. Spinoza distinguishes the practical demand for justice and charity from philosophy’s pursuit of truth, and he interprets miracles within the stable order of nature. Those positions challenge authorities who claim exclusive power to determine speculative belief. They do not simply abolish religion or turn every interpretation into private preference. Historical inquiry has rules, and civic order remains a genuine concern throughout a book written under conditions of confession, censorship, conflict, and political vulnerability.',
      'The final chapters defend a bounded freedom to philosophize and speak, arguing that attempts to command inward judgment can destabilize rather than secure a polity. Spinoza does not formulate an unrestricted modern rights charter, and his political arrangements leave exclusions and coercive boundaries that require criticism. The synagogue painting contributes atmosphere and institutional specificity, not direct proof of those arguments. Its open interior can easily tempt a story of uncomplicated Dutch tolerance, but the text and Spinoza’s own history resist that myth. Read together with explicit distance, the object and work reveal how worship, communal authority, state power, interpretation, and individual judgment occupied overlapping but contested spaces.',
    ],
    paragraphSourceIds: [['synagogue-rijks', 'synagogue-commons'], ['ttp-primary', 'spinoza-political'], ['ttp-primary', 'spinoza-political']],
    sources: [
      collection('synagogue-rijks', 'Rijksmuseum — Emanuel de Witte, Interior of the Portuguese Synagogue in Amsterdam', 'https://www.rijksmuseum.nl/en/collection/object/Interior%2Bof%2Bthe%2BPortuguese%2BSynagogue%2Bin%2BAmsterdam--7b93187abf920f79ed68677006c0d042'),
      collection('synagogue-commons', 'Wikimedia Commons — Rijksmuseum SK-A-3738 reproduction', 'https://commons.wikimedia.org/wiki/File:Interieur_van_de_Portugese_synagoge_te_Amsterdam_Rijksmuseum_SK-A-3738.jpeg'),
      primary('ttp-primary', 'Baruch Spinoza — Theological-Political Treatise, Project Gutenberg', 'https://www.gutenberg.org/ebooks/989'),
      academic('spinoza-political', 'Stanford Encyclopedia of Philosophy — Spinoza’s Political Philosophy', 'https://plato.stanford.edu/entries/spinoza-political/'),
    ],
    visitorGuide: [
      {heading: 'Reading the Treatise', items: [
        {label: 'Historical interpretation', description: 'Language, context, purpose, and textual comparison discipline the reading of Scripture.', sourceIds: ['ttp-primary', 'spinoza-political']},
        {label: 'Faith and philosophy', description: 'Spinoza distinguishes obedient practice from demonstrated truth without making either a synonym for every private opinion.', sourceIds: ['ttp-primary', 'spinoza-political']},
      ]},
      {heading: 'Keeping the context bounded', items: [
        {label: 'Later painting', description: 'The 1680 interior postdates the Treatise and is contextual rather than documentary evidence for it.', sourceIds: ['synagogue-rijks']},
        {label: 'Bounded toleration', description: 'Freedom of philosophizing operates within a political theory that still contains restrictions and contested exclusions.', sourceIds: ['ttp-primary', 'spinoza-political']},
      ]},
    ],
    resolution: 'Resolved: replaced a wholly false manuscript identity with de Witte’s verified Rijksmuseum painting, corrected attribution, date, institution, role, caption logic, and natural ratio, disclosed the rights-source distinction and temporal distance, sourced the Treatise claims, and linked the current Spinoza article.',
    lock: 'fnv1a64:02118d13812a6abe',
  },
  'conway-principles-vital-creation': {
    plaqueTitle: 'Franciscus Mercurius van Helmont',
    plaqueType: 'paired-or-grouped-historical-figures',
    canonicalContexts: [{kind: 'philosopher', id: 'anne-conway'}],
    articleTitle: 'Anne Conway',
    invitation: 'Lely’s 1670–1671 portrait shows Conway’s household associate and posthumous textual mediator, not the author or a title page of her Principles.',
    objectInterpretation: 'The installed object is Peter Lely’s 1670–1671 portrait of Franciscus Mercurius van Helmont, Tate N03583, not a 1690 Principia title page. Van Helmont participated in Conway’s intellectual household and the text’s posthumous transmission, but the portrait must not displace her authorship or establish the exact division of editorial labor.',
    overrides: {
      displayName: 'Franciscus Mercurius van Helmont',
      shortTitle: 'Van Helmont and Conway’s Text',
      workLabel: 'LIFETIME PORTRAIT · POSTHUMOUS MEDIATION',
      dateLabel: 'Peter Lely · 1670–1671 · Tate, N03583',
      frontSubtitle: 'A mediator in the network through which Conway’s vital philosophy survived',
      lead: 'Peter Lely’s portrait depicts Franciscus Mercurius van Helmont, not Anne Conway or her book. His proximity to her household and posthumous text makes mediation visible while leaving Conway’s authorship and philosophical originality central.',
    },
    paragraphs: [
      'Peter Lely’s portrait presents Franciscus Mercurius van Helmont in a brown cloak against a dark ground. The Tate record identifies the work, dates it to 1670–1671, and catalogs it as N03583; the installed derivatives match the portrait rather than the Principia title page named by the stale asset registry. The image is contemporary with Conway’s last decade and gives a face to one member of her network, but it shows no manuscript, translation, or act of authorship. Van Helmont’s association with Conway and the posthumous book matters historically. It must not turn him into her substitute, sole translator, or source of positions the surviving work attributes to her.',
      'The Principles of the Most Ancient and Modern Philosophy develops a theologically structured ontology of God, Christ or a mediating nature, and created beings. Creatures are living, perceptive, and capable of change; body and spirit differ by degree rather than forming inert matter and wholly separate mind. This framework contests Cartesian dualism and versions of materialism while refusing to make creation identical with the immutable God. Terms such as monism and trialism can illuminate parts of the architecture, but each can also flatten disputed relations among its three species. Conway’s arguments need to be read in their Christian, Platonist, kabbalistic, medical, and philosophical settings rather than secularized into a single modern category.',
      'Conway’s text reached readers through unusually complex mediation. It was published anonymously in Latin in 1690, after her death, and an English version followed in 1692. Surviving evidence does not provide a simple publication-ready autograph from which every intervention can be reconstructed. Van Helmont, Henry More, editors, translators, and printers belong to that history, as do the institutional exclusions that made household study and correspondence important. Mediation creates genuine questions about wording and editorial responsibility without erasing Conway as philosopher. The portrait’s proper role is therefore relational: it directs attention to how a woman’s systematic work survived through a network that could preserve, reshape, and overshadow it.',
    ],
    paragraphSourceIds: [['van-helmont-tate', 'van-helmont-commons'], ['conway-primary', 'conway-sep'], ['conway-sep', 'conway-edition']],
    sources: [
      collection('van-helmont-tate', 'Tate — Peter Lely, Franciscus Mercurius van Helmont, N03583', 'https://www.tate.org.uk/art/artworks/lely-franciscus-mercurius-van-helmont-n03583'),
      collection('van-helmont-commons', 'Wikimedia Commons — Lely portrait of Franciscus Mercurius van Helmont', 'https://commons.wikimedia.org/wiki/File:Peter_Lely_(1618-1680)_-_Frans_Mercurius_van_Helmont_-_N03583_-_National_Gallery.jpg'),
      primary('conway-primary', 'Anne Conway — Principles of the Most Ancient and Modern Philosophy', 'https://digital.library.upenn.edu/women/conway/principles/principles.html'),
      academic('conway-sep', 'Stanford Encyclopedia of Philosophy — Anne Conway', 'https://plato.stanford.edu/entries/conway/'),
      academic('conway-edition', 'Cambridge University Press — critical edition of Conway’s Principles', 'https://www.cambridge.org/core/books/anne-conway-the-principles-of-the-most-ancient-and-modern-philosophy/principles-of-the-most-ancient-and-modern-philosophy/E3779C64884C5F3661E56783E3C46A35'),
    ],
    visitorGuide: [
      {heading: 'Following Conway’s ontology', items: [
        {label: 'Three species', description: 'God, mediating Christ or middle nature, and mutable creatures structure the system without eliminating interpretive dispute.', sourceIds: ['conway-primary', 'conway-sep']},
        {label: 'Living creation', description: 'Creaturely body and spirit differ by degree within a vital, perceptive, morally changing order.', sourceIds: ['conway-primary', 'conway-sep']},
      ]},
      {heading: 'Tracking mediation', items: [
        {label: 'Posthumous publication', description: 'Anonymous Latin and later English editions carried the work after Conway’s death.', sourceIds: ['conway-sep', 'conway-edition']},
        {label: 'Network without displacement', description: 'Van Helmont helped the text’s transmission but does not replace Conway as author.', sourceIds: ['conway-sep', 'conway-edition']},
      ]},
    ],
    resolution: 'Resolved: followed the installed Lely portrait instead of a nonexistent Principia page, corrected object identity, institution, chronology, semantic role, and natural ratio, kept textual mediation from displacing Conway’s authorship, mapped the ontology claims, and linked the current Anne Conway article.',
    lock: 'fnv1a64:cb5f61ac69d52f2f',
  },
  'conway-intellectual-network': {
    plaqueTitle: 'Henry More',
    plaqueType: 'paired-or-grouped-historical-figures',
    canonicalContexts: [{kind: 'philosopher', id: 'anne-conway'}],
    articleTitle: 'Anne Conway',
    invitation: 'Loggan’s portrait marks one participant in Conway’s letter-based education and intellectual network without reducing her philosophy to male instruction.',
    objectInterpretation: 'The installed print is David Loggan’s portrait of Henry More, dated broadly 1679–1692 by the Rijksmuseum, RP-P-OB-46.333. Because the range crosses More’s 1687 death, it is not securely a lifetime portrait. It depicts More, not Conway, their correspondence, or the exact division of work in her posthumous publication.',
    overrides: {
      displayName: 'Henry More and Conway’s Intellectual Network',
      shortTitle: 'Henry More',
      workLabel: 'ENGRAVED PORTRAIT · CORRESPONDENCE NETWORK',
      dateLabel: 'David Loggan · 1679–1692 · Rijksmuseum, RP-P-OB-46.333',
      frontSubtitle: 'Letters, private study, disagreement, household exchange, and textual survival',
    },
    paragraphs: [
      'David Loggan’s engraved portrait identifies Henry More through an oval inscription and learned presentation. The Rijksmuseum dates the print broadly to 1679–1692 and catalogs it as RP-P-OB-46.333. Since that range extends beyond More’s death in 1687, the installed object cannot safely be called a secure lifetime portrait. Its natural ratio preserves the complete vertical print. More was an important correspondent and teacher in Anne Conway’s intellectual development, but the image portrays him alone. It cannot show their letters, prove agreement between them, or make a male face stand in for a woman whose own portrait is unavailable in this installation.',
      'Conway studied philosophy through books and sustained correspondence at a time when university attendance was closed to her. More guided reading and debated Platonism, Descartes, substance, spirit, body, and theodicy with her; Franciscus Mercurius van Helmont later became another important household interlocutor. These relationships supplied access and vocabulary without determining her conclusions. Conway criticizes Cartesian dualism, rejects inert matter, and develops a mutable living creation that differs from More’s positions in important ways. Illness and medical search formed part of the household context, yet they should not be used as a reductive explanation for her intellectual achievement or philosophical interests.',
      'The network continued after Conway’s death through manuscripts, translation, anonymous publication, and later reception, including Leibniz’s awareness of her work. Evidence for education and editorial labor remains partial, so confident stories about who supplied each sentence exceed the record. The better historical question is how correspondence, private libraries, visiting scholars, religious communities, and print enabled philosophy outside formal institutions while distributing authority unevenly. More’s portrait makes one node visible and risks magnifying him at the same time. Reading it critically keeps Conway’s disagreements, authorship, and systematic ambition in the foreground while acknowledging that the work visitors read is inseparable from collective transmission.',
    ],
    paragraphSourceIds: [['more-commons'], ['conway-sep', 'project-vox'], ['conway-sep', 'project-vox', 'conway-primary']],
    sources: [
      collection('more-commons', 'Rijksmuseum / Wikimedia Commons — David Loggan, portrait of Henry More', 'https://commons.wikimedia.org/wiki/File:Portret_van_Henry_More,_RP-P-OB-46.333.jpg'),
      primary('conway-primary', 'Anne Conway — Principles of the Most Ancient and Modern Philosophy', 'https://digital.library.upenn.edu/women/conway/principles/principles.html'),
      academic('conway-sep', 'Stanford Encyclopedia of Philosophy — Anne Conway', 'https://plato.stanford.edu/entries/conway/'),
      academic('project-vox', 'Project Vox — Anne Conway', 'https://projectvox.org/conway-1631-1679/'),
    ],
    visitorGuide: [
      {heading: 'Mapping the network', items: [
        {label: 'Correspondence education', description: 'Letters and private reading created philosophical access outside institutions closed to Conway.', sourceIds: ['conway-sep', 'project-vox']},
        {label: 'Disagreement within exchange', description: 'More supplied an interlocutor, not a complete blueprint for Conway’s living ontology.', sourceIds: ['conway-sep', 'conway-primary']},
      ]},
      {heading: 'Reading uneven survival', items: [
        {label: 'Household and print', description: 'Van Helmont, manuscripts, translators, editors, and printers affected how the posthumous text reached readers.', sourceIds: ['conway-sep', 'project-vox']},
        {label: 'Partial evidence', description: 'The exact division of educational and editorial labor cannot be reconstructed with certainty.', sourceIds: ['conway-sep']},
      ]},
    ],
    resolution: 'Resolved: verified Loggan’s Rijksmuseum portrait, retained the broad date range instead of inventing lifetime certainty, treated More as one network node without displacing Conway, mapped correspondence and transmission claims, preserved the natural ratio, and linked the current Anne Conway article.',
    lock: 'fnv1a64:bc398b4750a0bb7f',
  },
  'leibniz-monadology-perception': {
    plaqueTitle: 'Page Identified as a Monadology Manuscript',
    plaqueType: 'object-manuscript-site-or-archaeological-context',
    canonicalContexts: [{kind: 'philosopher', id: 'leibniz'}],
    articleTitle: 'Leibniz',
    invitation: 'A reproduction identified as a French Monadology manuscript opens Leibniz’s account of simple substances, perception, appetition, and expressive perspective.',
    objectInterpretation: 'The installed object is a reproduction identified by its Commons source as a French manuscript page of the Monadology attributed to Leibniz. No repository, shelfmark, or exact relation to a particular draft is supplied, so it cannot establish an autograph, finished text, public 1714 edition, or standard paragraph sequence.',
    overrides: {
      displayName: 'Page Identified as a Monadology Manuscript',
      shortTitle: 'The Monadology in Manuscript',
      workLabel: 'MANUSCRIPT REPRODUCTION · PROVENANCE INCOMPLETE',
      dateLabel: 'Identified with Leibniz’s Monadology · c. 1714 · repository unrecorded',
      frontSubtitle: 'Simple substances, perception, appetition, perspective, and a text left unpublished',
      lead: 'A French manuscript reproduction identified with the Monadology makes philosophical composition visible while its absent shelfmark and draft history set a firm limit on object-level certainty.',
    },
    paragraphs: [
      'Compact French handwriting fills the installed manuscript page, with corrections and spacing that register a text in material form. The Commons source identifies it as a Monadology manuscript associated with Gottfried Wilhelm Leibniz, but provides no repository, shelfmark, folio, or edition-specific catalog link. The Atlas therefore preserves the natural page ratio and the qualified phrase “identified as” rather than promoting the reproduction to a verified autograph or a securely located draft. The object cannot prove that the now-standard title, paragraph numbering, or arrangement already existed in finished public form in 1714. The work remained unpublished during Leibniz’s lifetime and survives within a much larger, multilingual manuscript corpus.',
      'The Monadology describes created reality through simple substances that have no physical parts. Simplicity does not make monads inert atoms: each has perceptions that represent multiplicity in unity and appetition that carries it from one perceptual state toward another. Apperception names reflective awareness, while petites perceptions help explain how countless unnoticed differences contribute to conscious experience. Calling monads “windowless” denies a transfer of physical pieces or images between substances; it does not mean that each is sealed into an unrelated private world. Every monad expresses the same universe from its own limited perspective, with degrees of clarity and organization.',
      'That expressive structure connects metaphysics, mind, body, and order. Leibniz explains coordinated changes through each substance’s internal principle and a divinely grounded harmony rather than through ordinary cross-substance transfer. Organisms are not merely heaps, and embodied perspectives matter to the hierarchy of perception. Yet the short late text is not a self-sufficient final system from which every Leibnizian doctrine can be read without the correspondence, essays, drafts, and earlier debates. The uncertain manuscript reproduction reinforces that warning. It directs attention to composition and transmission while the linked sources establish the concepts and preserve disagreements about idealism, corporeal substance, unconscious perception, and the work’s relation to Leibniz’s broader philosophy.',
    ],
    paragraphSourceIds: [['monadology-page', 'leibniz-sep'], ['monadology-primary', 'leibniz-mind'], ['monadology-primary', 'leibniz-sep', 'leibniz-mind']],
    sources: [
      collection('monadology-page', 'Wikimedia Commons — reproduction identified as a Leibniz Monadology manuscript', 'https://commons.wikimedia.org/wiki/File:Leibniz_Monadology_2.jpg'),
      primary('monadology-primary', 'Gottfried Wilhelm Leibniz — Monadology, Project Gutenberg', 'https://www.gutenberg.org/ebooks/17641'),
      academic('leibniz-sep', 'Stanford Encyclopedia of Philosophy — Gottfried Wilhelm Leibniz', 'https://plato.stanford.edu/entries/leibniz/'),
      academic('leibniz-mind', 'Stanford Encyclopedia of Philosophy — Leibniz’s Philosophy of Mind', 'https://plato.stanford.edu/entries/leibniz-mind/'),
    ],
    visitorGuide: [
      {heading: 'Entering the monad', items: [
        {label: 'Simple substance', description: 'A monad has no physical parts, but it possesses changing perceptions and an internal principle of change.', sourceIds: ['monadology-primary', 'leibniz-sep']},
        {label: 'Perception and appetition', description: 'Representation supplies a state; appetition names the passage toward a further state.', sourceIds: ['monadology-primary', 'leibniz-mind']},
      ]},
      {heading: 'Avoiding familiar traps', items: [
        {label: 'Windowless', description: 'No transferred physical item enters a monad; all still express one shared universe perspectivally.', sourceIds: ['monadology-primary', 'leibniz-sep']},
        {label: 'Unresolved manuscript', description: 'Without repository or shelfmark, the page cannot be tied securely to one draft or final sequence.', sourceIds: ['monadology-page', 'leibniz-sep']},
      ]},
    ],
    resolution: 'Resolved: kept the manuscript identity explicitly qualified by its missing repository and shelfmark, separated physical reproduction from textual conclusions, restored the exact natural ratio, supplied three mapped paragraphs and a concept-specific guide, and linked the current Leibniz article.',
    lock: 'fnv1a64:409928f5983fedc0',
  },
  'leibniz-preestablished-harmony': {
    plaqueTitle: 'Antoine Arnauld at His Writing Desk',
    plaqueType: 'paired-or-grouped-historical-figures',
    canonicalContexts: [{kind: 'philosopher', id: 'leibniz'}],
    articleTitle: 'Leibniz',
    invitation: 'Trouvain’s 1694 portrait shows a major Leibniz correspondent whose objections helped clarify individual substance and harmony; the visible paper is not their correspondence.',
    objectInterpretation: 'The installed object is Antoine Trouvain’s 1694 portrait of Antoine Arnauld at his writing desk, Rijksmuseum RP-P-OB-74.574, not a collage of Leibniz correspondence. Arnauld was a genuine interlocutor, but the sheet beneath his hand cannot be identified as a Leibniz letter or a diagram of pre-established harmony.',
    overrides: {
      displayName: 'Antoine Arnauld at His Writing Desk',
      shortTitle: 'Arnauld and Leibniz in Debate',
      workLabel: 'ENGRAVED PORTRAIT · PHILOSOPHICAL CORRESPONDENCE',
      dateLabel: 'Antoine Trouvain · 1694 · Rijksmuseum, RP-P-OB-74.574',
      frontSubtitle: 'Individual substance, expression, causal order, objection, and revision',
      lead: 'Antoine Arnauld appears at a desk in Trouvain’s portrait. His correspondence with Leibniz gives the object a factual relationship to the doctrine, but the visible page is neither a known letter nor an image of harmony.',
    },
    paragraphs: [
      'Antoine Trouvain’s engraved portrait places the theologian and philosopher Antoine Arnauld at a writing desk, one hand resting on a sheet. The Rijksmuseum identifies the 1694 work as RP-P-OB-74.574 and releases its reproduction openly. Installed scene and panel files match this vertical portrait, not the landscape montage of Leibniz papers asserted by the stale registry. The paper is visually suggestive but bibliographically anonymous: nothing in the collection record makes it a letter to or from Leibniz. Arnauld’s documented role as correspondent provides the relationship. Responsible interpretation must not transform a generic prop into a surviving exchange or the portrait into a literal diagram of metaphysics.',
      'In their 1686–1687 exchange, Arnauld presses Leibniz about the complete concept of an individual substance, contingency, divine choice, and whether every event is already contained in a person’s notion. Leibniz’s replies develop expression and the way each substance follows its own law while corresponding with the states of others. The mature doctrine of pre-established harmony denies ordinary causal transfer between created substances: changes arise from their internal principles, coordinated within an order grounded in God. This is not merely two clocks accidentally synchronized, and it does not eliminate every form of divine causality from Leibniz’s system.',
      'Mind-body relation provides the best-known application. Mental and bodily series agree without a push crossing from an immaterial mind into matter at each moment. Leibniz presents this as preferable to brute influx and to occasionalism’s repeated divine intervention, though his own accounts of concurrence, derivative force, and corporeal substance complicate any slogan. Arnauld’s objections matter because doctrines emerged through pressure from an informed critic rather than as isolated pronouncements. The portrait keeps that dialogical setting visible while refusing a counterfeit document claim. The correspondence and later Monadology must be dated and read within their distinct contexts rather than collapsed into one timeless formulation.',
    ],
    paragraphSourceIds: [['arnauld-rijks', 'arnauld-commons'], ['leibniz-causation', 'leibniz-primary'], ['leibniz-causation', 'monadology-primary']],
    sources: [
      collection('arnauld-rijks', 'Rijksmuseum — Antoine Trouvain, Antoine Arnauld at his writing desk', 'https://www.rijksmuseum.nl/nl/collectie/object/Portret-van-Antoine-Arnauld-aan-een-bureau--50a009cc44d000ab675910007bf71cf7'),
      collection('arnauld-commons', 'Wikimedia Commons — Trouvain portrait of Antoine Arnauld', 'https://commons.wikimedia.org/wiki/File:Portret_van_Antoine_Arnauld_aan_een_bureau,_RP-P-OB-74.574.jpg'),
      primary('leibniz-primary', 'Early Modern Texts — Leibniz primary-text collection', 'https://www.earlymoderntexts.com/authors/leibniz'),
      primary('monadology-primary', 'Gottfried Wilhelm Leibniz — Monadology, Project Gutenberg', 'https://www.gutenberg.org/ebooks/17641'),
      academic('leibniz-causation', 'Stanford Encyclopedia of Philosophy — Leibniz on Causation', 'https://plato.stanford.edu/entries/leibniz-causation/'),
    ],
    visitorGuide: [
      {heading: 'Following the exchange', items: [
        {label: 'Individual substance', description: 'Arnauld challenges what Leibniz’s complete-concept account means for contingency and identity.', sourceIds: ['leibniz-primary', 'leibniz-causation']},
        {label: 'Expression', description: 'Each substance represents the ordered universe from its own point of view.', sourceIds: ['leibniz-causation', 'monadology-primary']},
      ]},
      {heading: 'Distinguishing causal models', items: [
        {label: 'Pre-established harmony', description: 'Created substances unfold internally coordinated series rather than exchange states directly.', sourceIds: ['leibniz-causation', 'monadology-primary']},
        {label: 'Not a correspondence sheet', description: 'The paper in Trouvain’s portrait has no documented connection to Leibniz.', sourceIds: ['arnauld-rijks', 'arnauld-commons']},
      ]},
    ],
    resolution: 'Resolved: replaced a false Leibniz-papers identity with Trouvain’s verified Arnauld portrait, corrected institution, date, role, accessibility meaning, and drastic portrait ratio, bounded the visible paper, mapped the doctrine to primary and scholarly sources, and linked the current Leibniz article.',
    lock: 'fnv1a64:b354368e18a23a71',
  },
  'leibniz-new-essays-innateness': {
    plaqueTitle: 'John Locke',
    plaqueType: 'paired-or-grouped-historical-figures',
    canonicalContexts: [{kind: 'philosopher', id: 'leibniz'}],
    articleTitle: 'Leibniz',
    invitation: 'Kneller’s 1697 portrait shows the thinker answered by Leibniz’s New Essays; it is not an edition of the text and did not circulate as part of their public debate.',
    objectInterpretation: 'The installed object is Godfrey Kneller’s 1697 portrait of John Locke, State Hermitage Museum GE-1345, not the 1921 New Essays edition named by its stale registry. Locke is the work’s interlocutor, but the portrait neither depicts innateness nor supplies textual evidence for Leibniz’s unpublished reply.',
    overrides: {
      displayName: 'John Locke',
      shortTitle: 'Locke as Leibniz’s Interlocutor',
      workLabel: 'PORTRAIT · CONTEXT FOR THE NEW ESSAYS',
      dateLabel: 'Godfrey Kneller · 1697 · State Hermitage Museum, GE-1345',
      frontSubtitle: 'Experience, innate disposition, necessary truth, dialogue, and delayed publication',
      lead: 'Kneller’s portrait identifies the author whose Essay Leibniz answers. The installed image is contextual, while the New Essays and its publication history supply the philosophical evidence.',
    },
    paragraphs: [
      'Godfrey Kneller’s 1697 portrait of John Locke shows the philosopher in a brown mantle against a dark background. The State Hermitage Museum catalogs the painting as GE-1345, and the installed portrait derivatives match that work rather than a twentieth-century printed edition of Leibniz’s Nouveaux essais. Correcting the object changes its evidentiary role. Locke is the dialogue’s indispensable interlocutor, but his painted likeness contains no propositions about innate ideas and no pages of Leibniz’s response. It belongs to historical context. Public-domain status attaches to the old painting and its registered reproduction, while the claim-source record remains distinct from the philosophical texts.',
      'Leibniz composed the New Essays as a dialogue with Locke’s Essay, placing many Lockean positions in the mouth of Philalethes and his own replies in that of Theophilus. He rejects the idea that the mind begins as wholly blank, yet “innate” does not mean a stock of consciously present sentences. Dispositions, structures, and capacities make some truths available through reflection; the image of veined marble contrasts a shaped tendency with an empty tablet. Experience occasions thought and supplies contingent content, while necessary truths require principles that sensation alone cannot establish. Petites perceptions also challenge the assumption that every mental state must be consciously noticed.',
      'Chronology limits claims about influence. Leibniz completed the work around 1704 but withheld it after Locke’s death; it appeared only in 1765. The New Essays therefore did not enter Locke’s original public controversy as a timely published rebuttal, even though it records sustained engagement with his book. Its dialogue form can also blur the difference between direct quotation, paraphrase, and Leibniz’s construction of an opponent. The portrait should prompt visitors to keep persons, arguments, and publication events separate. It shows Locke near the moment of composition; the primary text and scholarship establish how Leibniz transformed that encounter into a theory of disposition, unconscious perception, experience, and reason.',
    ],
    paragraphSourceIds: [['locke-commons'], ['new-essays-primary', 'leibniz-mind'], ['new-essays-primary', 'leibniz-sep']],
    sources: [
      collection('locke-commons', 'Wikimedia Commons — Godfrey Kneller, John Locke, 1697, Hermitage GE-1345', 'https://commons.wikimedia.org/wiki/File:%27John_Locke%27_by_Godfrey_Kneller,_1697,_Hermitage.JPG'),
      primary('new-essays-primary', 'Early Modern Texts — Leibniz, New Essays on Human Understanding', 'https://www.earlymoderntexts.com/authors/leibniz'),
      academic('leibniz-sep', 'Stanford Encyclopedia of Philosophy — Gottfried Wilhelm Leibniz', 'https://plato.stanford.edu/entries/leibniz/'),
      academic('leibniz-mind', 'Stanford Encyclopedia of Philosophy — Leibniz’s Philosophy of Mind', 'https://plato.stanford.edu/entries/leibniz-mind/'),
    ],
    visitorGuide: [
      {heading: 'Entering the dialogue', items: [
        {label: 'Philalethes and Theophilus', description: 'The speakers stage Locke-facing and Leibnizian positions without functioning as simple verbatim transcripts.', sourceIds: ['new-essays-primary', 'leibniz-sep']},
        {label: 'Veined marble', description: 'Innateness is modeled as structured disposition, not a list of consciously present propositions.', sourceIds: ['new-essays-primary']},
      ]},
      {heading: 'Respecting chronology', items: [
        {label: 'Completed, then withheld', description: 'Written around 1704, the work was not published until 1765 and could not answer Locke publicly in his lifetime.', sourceIds: ['leibniz-sep']},
        {label: 'Portrait, not page', description: 'Kneller’s Locke supplies interlocutor context but no textual evidence for Leibniz’s account.', sourceIds: ['locke-commons']},
      ]},
    ],
    resolution: 'Resolved: replaced a nonexistent New Essays edition image with Kneller’s verified Locke portrait, corrected date, institution, semantic role, caption meaning, and natural ratio, made the 1704/1765 chronology explicit, mapped claims, and linked the current Leibniz article.',
    lock: 'fnv1a64:4896623ffdf5e5db',
  },
  'leibniz-clarke-space-time': {
    plaqueTitle: 'Samuel Clarke, D.D.',
    plaqueType: 'paired-or-grouped-historical-figures',
    canonicalContexts: [{kind: 'philosopher', id: 'leibniz'}],
    articleTitle: 'Leibniz',
    invitation: 'Vertue’s posthumous 1738 portrait introduces an independent philosopher whose 1715–1716 exchange with Leibniz joined space and time to theology and divine freedom.',
    objectInterpretation: 'The installed object is George Vertue’s posthumous 1738 engraved portrait of Samuel Clarke in the National Library of Wales Welsh Portrait Collection. It is not a document from the 1715–1716 correspondence, and Clarke should not be reduced to a mouthpiece for Newton.',
    overrides: {
      displayName: 'Samuel Clarke, D.D.',
      shortTitle: 'Clarke in Posthumous Portraiture',
      workLabel: 'POSTHUMOUS PORTRAIT · PHILOSOPHICAL EXCHANGE',
      dateLabel: 'George Vertue · 1738 · National Library of Wales',
      frontSubtitle: 'Space, time, sufficient reason, divine freedom, relation, and disagreement',
    },
    paragraphs: [
      'George Vertue’s 1738 engraving presents Samuel Clarke in clerical dress within a lettered oval. The National Library of Wales record places it in the Welsh Portrait Collection, and its date makes it explicitly posthumous: Clarke died in 1729. Installed derivatives preserve the full portrait at its narrow natural ratio. The image is therefore reception portraiture rather than a document of the Leibniz–Clarke correspondence conducted in 1715–1716 and first collected in 1717. It identifies a participant but cannot show the exchange itself, guarantee how contemporaries saw Clarke, or make him a passive proxy whose positions belong entirely to Isaac Newton.',
      'Leibniz argues that space is an order of coexistences and time an order of successions rather than self-subsisting containers. His principles of sufficient reason and the identity of indiscernibles press against a universe that could be shifted wholesale without any observable difference, because such a choice would lack reason. Clarke defends a more absolute account connected to divine presence and agency and worries that Leibniz’s framework constrains God and weakens real causal action. Their disagreement is simultaneously metaphysical, theological, and physical. Calling it simply a contest between relational and absolute space is useful only if those adjoining commitments remain visible.',
      'Neither position should be translated directly into twentieth-century physics. Leibniz is not offering Einsteinian spacetime in advance, and Clarke’s account is not merely an obsolete box around objects. Their letters test what counts as a sufficient explanation, whether indiscernible worlds can differ, how God chooses and acts, and what the new natural philosophy entails for providence. Clarke develops arguments rather than ventriloquizing Newton, while Leibniz’s relational vocabulary does not settle every question about bodies or force. The portrait’s historical distance helps make the correct relation clear: it remembers one disputant, while the correspondence supplies the claims and the linked article locates Leibniz’s position within a broader system.',
    ],
    paragraphSourceIds: [['clarke-portrait'], ['clarke-primary', 'leibniz-physics', 'clarke-sep'], ['clarke-primary', 'leibniz-physics', 'clarke-sep']],
    sources: [
      collection('clarke-portrait', 'National Library of Wales / Wikimedia Commons — George Vertue, Samuel Clarke D.D., 1738', 'https://commons.wikimedia.org/wiki/File:Portrait_of_Samuel_Clarke_D._D_(4671390).jpg'),
      primary('clarke-primary', 'Early Modern Texts — Leibniz–Clarke correspondence', 'https://www.earlymoderntexts.com/assets/pdfs/leibniz1715.pdf'),
      academic('leibniz-physics', 'Stanford Encyclopedia of Philosophy — Leibniz’s Philosophy of Physics', 'https://plato.stanford.edu/entries/leibniz-physics/'),
      academic('clarke-sep', 'Stanford Encyclopedia of Philosophy — Samuel Clarke', 'https://plato.stanford.edu/entries/clarke/'),
    ],
    visitorGuide: [
      {heading: 'Locating the disagreement', items: [
        {label: 'Relational order', description: 'Leibniz treats space and time as orders among things and events, not independent containers.', sourceIds: ['clarke-primary', 'leibniz-physics']},
        {label: 'Clarke’s absolute account', description: 'Clarke links space and time to divine presence, agency, and a different explanatory framework.', sourceIds: ['clarke-primary', 'clarke-sep']},
      ]},
      {heading: 'Avoiding hindsight', items: [
        {label: 'Sufficient reason', description: 'Leibniz asks what could justify a choice between worlds with no discernible difference.', sourceIds: ['clarke-primary', 'leibniz-physics']},
        {label: 'No Einstein shortcut', description: 'Relational language does not make Leibniz a direct anticipator of modern spacetime theory.', sourceIds: ['leibniz-physics', 'clarke-sep']},
      ]},
    ],
    resolution: 'Resolved: verified Vertue’s posthumous Clarke portrait and its Welsh collection context, separated image date from the 1715–1717 correspondence, restored the exact narrow ratio, preserved Clarke’s independent position and the theology of the exchange, mapped claims, and linked the current Leibniz article.',
    lock: 'fnv1a64:7007868dee571710',
  },
  'leibniz-binary-symbolic-reason': {
    plaqueTitle: 'Table of the Numbers 0–32 in Binary Figures',
    plaqueType: 'concept-argument-diagram-or-method',
    canonicalContexts: [{kind: 'philosopher', id: 'leibniz'}],
    articleTitle: 'Leibniz',
    invitation: 'Leibniz’s 1703 table demonstrates positional binary arithmetic while its global and technological afterlives require careful, non-anachronistic comparison.',
    objectInterpretation: 'The installed object is Leibniz’s table of decimal numbers 0–32 rendered in binary figures, published in the 1703 Explication de l’arithmétique binaire and reproduced through the Académie des sciences/Gallica source chain. It demonstrates notation and operations, not electronic circuitry or programmable computation.',
    overrides: {
      displayName: 'Table of the Numbers 0–32 in Binary Figures',
      shortTitle: 'Leibniz’s Binary Table',
      workLabel: 'PRINTED TABLE · POSITIONAL ARITHMETIC',
      dateLabel: 'Gottfried Wilhelm Leibniz · Académie des sciences, 1703',
      frontSubtitle: 'Zero, one, place value, calculation, symbolic ambition, and cross-cultural interpretation',
    },
    paragraphs: [
      'The installed table aligns ordinary decimal numbers from zero through thirty-two with sequences composed only of zero and one. It was published with Leibniz’s Explication de l’arithmétique binaire in 1703 through the Académie royale des sciences; the registered Gallica and Commons source chain treats the page as public domain. Preserving its tall natural ratio keeps headings, columns, and the lower explanatory material visible. The object establishes a positional notation and examples of arithmetic representation. It contains no electronic switches, stored program, or computer architecture, so resemblance to later digital systems must not become a claim that the page depicts or invents modern computing.',
      'Binary notation expresses number through powers of two. A digit’s value depends on its position, allowing addition, subtraction, multiplication, and division with only two figures. Leibniz connected that economy to a broader interest in symbolic calculation and in methods that might discipline reasoning, but a numerical system is not identical with a universal logical calculus or a mechanical calculator. The page’s clarity comes from conventions visitors can learn and reproduce. Its importance lies in a historically specific mathematical publication and the ambitions attached to it, not in a teleological march toward devices that required very different materials, theories, institutions, and engineering.',
      'Leibniz also compared binary arithmetic with diagrams sent by the Jesuit Joachim Bouvet and associated with the Yijing. That encounter records global circulation and Leibniz’s selective theological interpretation, including his interest in creation from unity and nothing. Scholarship disputes how the diagram’s ordering and attribution should be described; it should not be flattened into the assertion that an ancient Chinese classic secretly encoded a modern binary computer. Comparison can reveal formal analogy while preserving different intellectual purposes and transmission histories. The table therefore invites two disciplines at once: follow the operations exactly, and resist stories that make either Chinese diagrams or Leibniz’s notation meaningful only because of later technology.',
    ],
    paragraphSourceIds: [['binary-page'], ['binary-page', 'leibniz-sep'], ['binary-study', 'leibniz-sep']],
    sources: [
      collection('binary-page', 'Académie des sciences / Gallica / Wikimedia Commons — Leibniz binary table, 1703', 'https://commons.wikimedia.org/wiki/File:Leibniz_binary_system_1703.png'),
      academic('binary-study', 'Science in Context — Fu Xi diagram and Leibnizian binary analogy', 'https://www.cambridge.org/core/journals/science-in-context/article/abs/is-the-fuxi-liushisi-gua-fangwei-diagram-attributed-to-shao-yong-binary-clarifying-a-consequence-of-its-analogy-with-the-binary-arithmetic-of-leibniz/9BA1DB9CFF13D5BEADCAF8FF954108AC'),
      academic('leibniz-sep', 'Stanford Encyclopedia of Philosophy — Gottfried Wilhelm Leibniz', 'https://plato.stanford.edu/entries/leibniz/'),
    ],
    visitorGuide: [
      {heading: 'Reading the table', items: [
        {label: 'Positional notation', description: 'A zero or one takes value from its place, representing successive powers of two.', sourceIds: ['binary-page']},
        {label: 'Arithmetic, not circuitry', description: 'The printed examples concern number representation and operation, not electronic architecture.', sourceIds: ['binary-page', 'leibniz-sep']},
      ]},
      {heading: 'Handling comparison carefully', items: [
        {label: 'Bouvet’s mediation', description: 'Leibniz received and interpreted diagrams through a particular missionary correspondence and theological frame.', sourceIds: ['binary-study']},
        {label: 'Formal analogy', description: 'A pattern can resemble binary order without sharing the purpose or history of Leibnizian arithmetic.', sourceIds: ['binary-study', 'leibniz-sep']},
      ]},
    ],
    resolution: 'Resolved: verified the 1703 binary table and source chain, restored its exact natural portrait ratio, separated positional arithmetic from modern computers, qualified the Bouvet/Yijing comparison, supplied three claim-mapped paragraphs and a specific guide, and linked the current Leibniz article.',
    lock: 'fnv1a64:74d2c2a8d38f8859',
  },
};

const reviewMethod = 'Galleries 12–13 supplemental review: exactly three concurrent GPT-5.6 Terra/High read-only evidence scopes of nine, nine, and eight non-overlapping exhibits were reconciled by the Sol parent across installed-object identity, attribution, dating, institution, provenance, rights, captions, alt text, claim-level sources, factual plaques, canonical relationships, exact article actions, current review locks, natural-ratio mounting, and desktop, mobile, and staged-3D presentation.';

const visualReview = (id: string): NonNullable<NonNullable<MuseumSupplementalExhibit['review']>['visualReview']> => ({
  desktop: {
    reviewedOn: '2026-08-20',
    viewport: '1440×900',
    evidence: `Direct route inspected with the full uncropped object preview, three untitled sourced paragraphs, subject-specific guide, factual plaque relationship, complete article action, and no horizontal overflow. Evidence: docs/visual-validation/gallery-12-13-supplementals/desktop/${id}.png`,
  },
  mobile: {
    reviewedOn: '2026-08-20',
    viewport: '390×844',
    evidence: `Direct route inspected with a wrapped factual title, full aspect-safe object preview, scrollable interpretation, complete controls, and no horizontal overflow. Evidence: docs/visual-validation/gallery-12-13-supplementals/mobile/${id}.png`,
  },
  threeDimensional: {
    reviewedOn: '2026-08-20',
    viewport: '1280×720 fresh direct-route session',
    evidence: `Fresh direct-route session inspected after closing the detail view: authored viewpoint, factual two-level plaque, distinct installation, working visit controls, and natural-ratio media mount. Evidence: docs/visual-validation/gallery-12-13-supplementals/staged-3d/${id}.png`,
  },
});

export const reviewRationalismSupplementalExhibit = (input: MuseumSupplementalExhibit): MuseumSupplementalExhibit => {
  const reviewed = evidence[input.id];
  if (!reviewed) throw new Error(`Missing Gallery 13 review evidence for ${input.id}.`);
  if (!input.presentation) throw new Error(`Missing Gallery 13 presentation for ${input.id}.`);
  const evidenceLabel = reviewed.overrides?.dateLabel ?? input.dateLabel;
  return {
    ...input,
    ...reviewed.overrides,
    sections: reviewed.paragraphs.map((paragraph, index) => ({
      heading: '',
      paragraphs: [paragraph],
      sourceIds: reviewed.paragraphSourceIds[index],
    })),
    sources: reviewed.sources,
    visitorGuide: reviewed.visitorGuide,
    objectInterpretation: reviewed.objectInterpretation,
    presentation: {
      ...input.presentation,
      panelKicker: 'Gallery 13 supplemental exhibit',
      proximityKicker: reviewed.plaqueTitle,
      factRows: [
        {label: 'Object', value: reviewed.plaqueTitle},
        {label: 'Evidence', value: evidenceLabel},
        {label: 'Atlas route', value: reviewed.articleTitle},
      ],
      articleActionLabel: `Read the full sourced ${reviewed.articleTitle} article`,
      exhibitLayout: 'object-led',
    },
    wallPlaque: {
      type: reviewed.plaqueType,
      title: reviewed.plaqueTitle,
      invitation: reviewed.invitation,
      canonicalContexts: reviewed.canonicalContexts,
    },
    review: {
      status: 'standard-compliant',
      reviewedOn: '2026-08-20',
      method: reviewMethod,
      resolution: reviewed.resolution,
      lock: reviewed.lock,
      visualReview: visualReview(input.id),
    },
  };
};
