import assert from 'node:assert/strict';
import {readFile, writeFile} from 'node:fs/promises';
import {loadAppData} from './loadAppData.mjs';
import {
  generatedArtifactMatches,
  normalizeGeneratedArtifactEol,
} from './generatedArtifactIntegrity.mjs';

const OUTPUT_URL = new URL('../src/data/generated/publicCollectionCounts.ts', import.meta.url);
const README_URL = new URL('../README.md', import.meta.url);
const ROADMAP_URL = new URL('../docs/content-roadmap.md', import.meta.url);
const METHODOLOGY_URL = new URL('../src/components/Editorial/EditorialMethodology.tsx', import.meta.url);
const EDITORIAL_STANDARD_URL = new URL('../docs/standards/editorial-program.md', import.meta.url);
const checkOnly = process.argv.includes('--check');
const START_MARKER = '<!-- public-collection-counts:start -->';
const END_MARKER = '<!-- public-collection-counts:end -->';

const data = await loadAppData();
const articleByKey = new Map(data.canonicalArticles.map((article) => [
  `${article.category}:${article.canonicalId}`,
  article,
]));
const currentClaimReviewedArticles = data.canonicalArticles.filter(({editorialRecord}) =>
  data.reviewLock.effectiveEditorialStatus(editorialRecord) === 'claim-reviewed');
const primaryExhibits = data.museumCanonicalProgram.flatMap((hall) => hall.rooms.flatMap((room) =>
  room.exhibits.map((exhibit) => ({hallId: hall.id, exhibit})),
));
const interpretationByRef = new Map(data.museumInterpretations.map((interpretation) => [
  `${interpretation.hallId}:${interpretation.id}`,
  interpretation,
]));
const primaryStatuses = primaryExhibits.map(({hallId, exhibit}) => {
  const articleCategory = exhibit.entityKind === 'philosopher' ? 'philosopher' : 'philosophy';
  const article = articleByKey.get(`${articleCategory}:${exhibit.entityId}`);
  const interpretation = interpretationByRef.get(`${hallId}:${exhibit.id}`);
  assert(article, `Primary exhibit ${hallId}/${exhibit.id} has no canonical article.`);
  assert(interpretation, `Primary exhibit ${hallId}/${exhibit.id} has no interpretation.`);
  return data.exhibitReview.effectiveMuseumExhibitReviewStatus(interpretation, article.editorialRecord);
});
const supplementalStatuses = data.museumSupplementalExhibits.map(({hallId, exhibit}) => {
  const authored = data.exhibitReview.authoredMuseumExhibitReviewStatus(exhibit);
  if (authored === 'unreviewed') return {authored, effective: authored};
  const target = exhibit.articleRoute?.kind === 'philosopher'
    ? `philosopher:${exhibit.articleRoute.philosopherId}`
    : exhibit.articleRoute?.kind === 'branch'
      ? `philosophy:${exhibit.articleRoute.branchId}`
      : null;
  const article = target ? articleByKey.get(target) : undefined;
  return {
    authored,
    effective: article
      ? data.exhibitReview.effectiveMuseumExhibitReviewStatus(exhibit, article.editorialRecord)
      : 'out-of-date',
  };
});

const counts = {
  canonicalArticles: {
    total: data.canonicalArticles.length,
    philosophers: data.canonicalArticles.filter(({category}) => category === 'philosopher').length,
    philosophies: data.canonicalArticles.filter(({category}) => category === 'philosophy').length,
    currentClaimReviewed: currentClaimReviewedArticles.length,
  },
  primaryExhibits: {
    total: primaryExhibits.length,
    standardCompliant: primaryStatuses.filter((status) => status === 'standard-compliant').length,
    unreviewed: primaryStatuses.filter((status) => status === 'unreviewed').length,
  },
  supplementalExhibits: {
    total: supplementalStatuses.length,
    reviewed: supplementalStatuses.filter(({authored}) => authored !== 'unreviewed').length,
    standardCompliant: supplementalStatuses.filter(({effective}) => effective === 'standard-compliant').length,
    backlog: supplementalStatuses.filter(({authored}) => authored === 'unreviewed').length,
  },
  museumStops: primaryExhibits.length + supplementalStatuses.length,
};

assert.equal(
  counts.canonicalArticles.philosophers + counts.canonicalArticles.philosophies,
  counts.canonicalArticles.total,
  'Public article composition must account for every canonical article.',
);
assert.equal(
  counts.supplementalExhibits.reviewed + counts.supplementalExhibits.backlog,
  counts.supplementalExhibits.total,
  'Reviewed and backlog supplemental counts must account for the full supplemental program.',
);

const generatedModule = `// Generated by npm run compile:public-counts. Do not edit by hand.\nexport const PUBLIC_COLLECTION_COUNTS = ${JSON.stringify(counts, null, 2)} as const;\n`;
const readmeBlock = `${START_MARKER}
The current generated reports record **${counts.canonicalArticles.currentClaimReviewed} of ${counts.canonicalArticles.total} canonical articles as currently claim-reviewed**—${counts.canonicalArticles.philosophers} philosopher profiles and ${counts.canonicalArticles.philosophies} articles on philosophies, branches, schools, traditions, movements, methods, and frameworks—and **${counts.primaryExhibits.standardCompliant} of ${counts.primaryExhibits.total} primary Museum exhibits as standard-compliant**. Article depth, claim review, and primary exhibit review remain separate milestones; completing one does not confer another.

The Museum also contains **${counts.supplementalExhibits.total} supplemental/context exhibits**: **${counts.supplementalExhibits.reviewed} reviewed supplementals** and **${counts.supplementalExhibits.backlog} explicit backlog supplementals**. Together, the ${counts.primaryExhibits.total} primary and ${counts.supplementalExhibits.total} supplemental exhibits make **${counts.museumStops} interpreted Museum stops**.
${END_MARKER}`;
const roadmapBlock = `${START_MARKER}
- **${counts.canonicalArticles.total} canonical full articles:** ${counts.canonicalArticles.philosophers} philosopher profiles and ${counts.canonicalArticles.philosophies} articles on philosophies, branches, schools, traditions, movements, methods, and frameworks; ${counts.canonicalArticles.currentClaimReviewed} of ${counts.canonicalArticles.total} are currently claim-reviewed.
- **${counts.primaryExhibits.total} primary Museum exhibits:** ${counts.primaryExhibits.standardCompliant} of ${counts.primaryExhibits.total} are standard-compliant under the separate primary exhibit-review standard.
- **${counts.supplementalExhibits.total} supplemental Museum exhibits:** ${counts.supplementalExhibits.reviewed} reviewed and ${counts.supplementalExhibits.backlog} explicit backlog.
- **26 curated/open galleries and 105 rooms:** ${counts.museumStops} interpreted stops on one connected public level.
${END_MARKER}`;

const extractCountBlock = (source, relativePath) => {
  const normalized = normalizeGeneratedArtifactEol(source);
  const start = normalized.indexOf(START_MARKER);
  const end = normalized.indexOf(END_MARKER);
  assert(start >= 0 && end > start, `${relativePath} is missing the public collection-count markers.`);
  assert.equal(normalized.indexOf(START_MARKER, start + START_MARKER.length), -1, `${relativePath} repeats the public collection-count start marker.`);
  assert.equal(normalized.indexOf(END_MARKER, end + END_MARKER.length), -1, `${relativePath} repeats the public collection-count end marker.`);
  return normalized.slice(start, end + END_MARKER.length);
};

const [readme, roadmap, methodology, editorialStandard] = await Promise.all([
  readFile(README_URL, 'utf8'),
  readFile(ROADMAP_URL, 'utf8'),
  readFile(METHODOLOGY_URL, 'utf8'),
  readFile(EDITORIAL_STANDARD_URL, 'utf8'),
]);
assert.equal(extractCountBlock(readme, 'README.md'), readmeBlock, 'README.md public collection counts are stale.');
assert.equal(extractCountBlock(roadmap, 'docs/content-roadmap.md'), roadmapBlock, 'docs/content-roadmap.md public collection counts are stale.');

const caveat = 'internal, AI-assisted editorial review states';
const independence = 'independent academic or peer review';
assert(readme.includes(caveat) && readme.includes(independence), 'README.md must preserve the internal, AI-assisted, non-peer-review caveat.');
assert(roadmap.includes(caveat) && roadmap.includes(independence), 'docs/content-roadmap.md must preserve the internal, AI-assisted, non-peer-review caveat.');
assert(methodology.includes(caveat) && methodology.includes(independence), 'EditorialMethodology.tsx must preserve the internal, AI-assisted, non-peer-review caveat.');
assert(
  methodology.includes("from '../../data/generated/publicCollectionCounts'"),
  'EditorialMethodology.tsx must consume the lightweight generated public-count module.',
);
const methodologyModuleSpecifiers = [
  ...methodology.matchAll(/\bfrom\s*['"]([^'"]+)['"]/gu),
  ...methodology.matchAll(/\bimport\s*['"]([^'"]+)['"]/gu),
  ...methodology.matchAll(/\bimport\s*\(\s*['"]([^'"]+)['"]/gu),
].map((match) => match[1]);
const allowedRelativeMethodologyImports = new Set(['../../data/generated/publicCollectionCounts']);
for (const specifier of methodologyModuleSpecifiers.filter((value) => value.startsWith('.'))) {
  assert(
    allowedRelativeMethodologyImports.has(specifier),
    `EditorialMethodology.tsx has an unapproved relative import that could expand its route chunk: ${specifier}`,
  );
}
assert(
  editorialStandard.includes('The initial universal-depth migration closed on 3 August 2026 with all 191 canonical articles meeting the floor.'),
  'The historically accurate 191-article initial migration statement must remain intact.',
);

if (checkOnly) {
  const committed = await readFile(OUTPUT_URL, 'utf8');
  assert(generatedArtifactMatches(committed, generatedModule), 'src/data/generated/publicCollectionCounts.ts is stale. Run npm run compile:public-counts.');
} else {
  await writeFile(OUTPUT_URL, generatedModule, 'utf8');
}

console.log(
  `${checkOnly ? 'Verified' : 'Generated'} public collection counts: `
  + `${counts.canonicalArticles.currentClaimReviewed}/${counts.canonicalArticles.total} claim-reviewed articles; `
  + `${counts.primaryExhibits.standardCompliant}/${counts.primaryExhibits.total} compliant primary exhibits; `
  + `${counts.supplementalExhibits.reviewed} reviewed and ${counts.supplementalExhibits.backlog} backlog supplementals; `
  + `${counts.museumStops} Museum stops.`,
);
