import {useMemo,useState} from 'react';
import {ArrowRight,BookOpen,Clock3,GitCompareArrows,GitBranch,HelpCircle,Landmark,Link2,Network,Search,Scale,UserRound} from 'lucide-react';
import {philosophers,philosopherById} from '../../data/philosophers';
import {branchById} from '../../data/branches';
import {PageHead} from '../BigHistory/BigHistoryView';
import {PhilosopherPortrait} from '../PhilosopherPortrait/PhilosopherPortrait';
import type {ReadingEntry} from '../../types/philosophy';

export function PhilosopherProfile({selectedId,onSelect,onBranch,onCompare}:{selectedId:string;onSelect:(id:string)=>void;onBranch:(id:string)=>void;onCompare:(a:string,b:string)=>void}){
  const[q,setQ]=useState('');
  const list=useMemo(()=>{const needle=q.toLowerCase();return philosophers.filter(p=>`${p.name} ${p.tradition} ${p.mainIdeas.join(' ')}`.toLowerCase().includes(needle))},[q]);
  const p=philosopherById(selectedId)??philosophers[0];
  const image=p.image;
  return <div className="page philosopher-atlas-page"><PageHead eyebrow="Thinkers in context" title="Philosopher Profiles" text="Biographies, questions, works, and influence routes show how a thinker changed the conversation."/>
    <div className="profiles-layout"><aside className="profile-list"><label><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Find a thinker, tradition, or idea…"/></label>{list.map(x=><button className={`selectable-card ${p.id===x.id?'active is-selected':''}`} key={x.id} onClick={()=>onSelect(x.id)}><PhilosopherPortrait philosopher={x}/><span><b>{x.name}</b><small>{x.lifespan} · {x.tradition}</small></span><ArrowRight size={13}/></button>)}</aside>
      <article className="profile-detail deep-profile" style={{'--accent':p.color} as React.CSSProperties}>
        <div className="profile-hero"><PhilosopherPortrait philosopher={p} size="large"/><div><div className="eyebrow">{p.region} · {p.tradition}</div><h1>{p.name}</h1><p>{p.lifespan}</p>{image?.url&&<small className="image-credit">{image.credit}{image.license?` · ${image.license}`:''}</small>}</div></div>
        <div className="profile-actions"><button className="btn btn-secondary" onClick={()=>onCompare(p.id,philosophers.find(x=>x.id!==p.id)!.id)}><GitCompareArrows size={16}/> Add to compare</button>{p.primaryBranchIds[0]&&<button className="btn btn-primary" onClick={()=>onBranch(p.primaryBranchIds[0])}>Show where they fit <ArrowRight size={16}/></button>}</div>
        <section className="lead-card static-info-card"><Landmark/><div><span>Short biography</span><h2>{p.contributionSummary}</h2><p>{p.shortBio??p.beginnerExplanation}</p></div></section>
        <div className="profile-grid profile-context-grid"><section className="static-info-card"><h3><Clock3 size={14}/> Historical context</h3><p>{p.historicalContext}</p></section><section className="static-info-card"><h3><HelpCircle size={14}/> Central problem</h3><p>{p.centralQuestions?.[0]??p.beginnerExplanation}</p></section></div>
        <DepthSection title="Biography and intellectual development" icon={<UserRound/>} open><div className="prose-stack">{(p.extendedBio??[p.lifeStory]).map(text=><p key={text}>{text}</p>)}</div>{p.lifeEvents&&<div className="mini-timeline">{p.lifeEvents.map(event=><div key={`${event.label}-${event.year??event.approximateYear}`}><b>{event.year??event.approximateYear??'Approx.'}</b><span><strong>{event.label}</strong>{event.description}</span></div>)}</div>}{p.intellectualDevelopment&&<ol className="reading-list">{p.intellectualDevelopment.map(item=><li key={item}>{item}</li>)}</ol>}</DepthSection>
        <DepthSection title="Central questions and major ideas" icon={<Network/>} open><div className="question-grid">{p.centralQuestions?.map((question,index)=><div className="number-card static-info-card" key={question}><span>{String(index+1).padStart(2,'0')}</span><h3>{question}</h3></div>)}</div><div className="deep-idea-grid">{p.majorIdeasDetailed?.map(idea=><article className="static-info-card" key={idea.name}><h3>{idea.name}</h3><p>{idea.explanation}</p><small>{idea.whyItMatters}</small></article>)}</div></DepthSection>
        <DepthSection title="Influence and interpretive tensions" icon={<Network/>}><div className="depth-columns"><div><h3>Influences received</h3><ul className="clean-list">{p.influencesReceived?.map(item=><li key={item}>{item}</li>)}</ul></div><div><h3>Influence on later thought</h3><ul className="clean-list">{p.influenceOnLaterThought?.map(item=><li key={item}>{item}</li>)}</ul></div></div>{p.controversiesOrInterpretiveTensions?.map(item=><p className="interpretive-note" key={item}><Scale size={14}/>{item}</p>)}</DepthSection>
        <DepthSection title="Works and reading paths" icon={<BookOpen/>} open><div className="deep-work-grid">{p.keyWorksDetailed?.map(work=><article className="static-info-card" key={work.title}><div className="eyebrow">{work.year??work.approximateYear??'Major work'}</div><h3>{work.title}</h3><p>{work.summary}</p><small>{work.whyItMatters}</small></article>)}</div><div className="depth-columns"><ReadingRoute title="Begin here" items={p.beginnerReadingPath}/><ReadingRoute title="Continue deeper" items={p.advancedReadingPath}/></div></DepthSection>
        <DepthSection title="Branches in the atlas" icon={<GitBranch/>}><div className="branch-contribution-list">{p.branchContributions?.map(item=><button className="selectable-card" key={item.branchId} onClick={()=>onBranch(item.branchId)}><span className="branch-dot" style={{background:branchById(item.branchId)?.color}}/><span><b>{branchById(item.branchId)?.name}</b><small>{item.summary}</small></span><ArrowRight size={13}/></button>)}</div></DepthSection>
        {p.sourceLinks&&p.sourceLinks.length>0&&<DepthSection title="Sources and further reference" icon={<Link2/>}>{p.sourceLinks.map(link=><a className="source-link" href={link.url} key={link.url} target="_blank" rel="noreferrer"><span><b>{link.label}</b><small>{link.type}{link.notes?` · ${link.notes}`:''}</small></span><ArrowRight size={13}/></a>)}</DepthSection>}
      </article>
    </div>
  </div>;
}

function DepthSection({title,icon,open=false,children}:{title:string;icon:React.ReactNode;open?:boolean;children:React.ReactNode}){return <details className="depth-section" open={open}><summary><span>{icon}<b>{title}</b></span><small>Expand exhibit</small></summary><div className="depth-section-body">{children}</div></details>}
function ReadingRoute({title,items=[]}:{title:string;items?:ReadingEntry[]}){return <div><h3>{title}</h3>{items.length?<ol className="structured-reading-list">{items.map(item=><li key={`${item.author}-${item.title}`}><b>{item.title}</b><span>{item.author} · {item.difficulty} · {item.type}</span><p>{item.whyRead}</p></li>)}</ol>:<p className="muted-note">No additional route has been curated yet.</p>}</div>}
